### ISSUE TITLE
[Feature Request] doi2arc: retrieve publication data based on DOI

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#10]
I found the [crossref API](https://www.crossref.org/documentation/retrieve-metadata/rest-api/tips-for-using-the-crossref-rest-api/) to be easiest to handle and most complete (compared to e.g. data cite API) 

`curl https://api.crossref.org/works/<doi> > crossref.json`

```bash
curl https://api.crossref.org/works/10.1104/pp.15.01076 > crossref.json
```

**Comment by JonasLukasczyk** [comment]
Supported with 7e78e39788cedcc5797ccb28447adf292ad12617
