### ISSUE TITLE
[Feature Request] Add a README template and LICENSE

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/ARCitect#100]
**Is your feature request related to a problem? Please describe.**
When creating an ARC with the ARCitect most users might not know that adding a readme and license is possible and desirable. In case the ARC is set to publi in the future this is protective to forget about this and can be replaced if a user wants a different license. ARCs without a README are also not desirable right from the beginning - imo

**Describe the solution you'd like**
Add a README template and LICENSE per default or allow to select one. Suggested LICENSE: CC-BY 4.0

**Comment by Freymaurer** [comment]
Hello @andreaschrader i saw all the issues you opened today and will try to adress them soon. Sadly i have a lot of projects to do in paralell which will take some time.

I can see the option to add a license by default, but i need to hear what @CMR248 and @Brilator think about this.

About the README.md, currently the ARCitect adds a README.md to all studies and assays by default. Where would you like to see additional readmes?

**Comment by Brilator** [comment]
- Default README.md in root with title = Investigation Identifier (= ARC name) would definitely make sense

I'd also appreciate the option to easily add a LICENCE to ARC root (similar to the feature in GitLab on top of the ARC). 
However, I would not suggest to add a default CC-BY. 
And unfortunately the GitLab dropdown does not include CC-BY 4.0.

**Comment by andreaschrader** [comment]
Hi @Freymaurer, sorry for the bulk of issues. This was a collection from the current hackathon. I was looking for a README in the root of the repo.
Yes, CC-BY 4.0 is not offered by github for selection but it is the most common for (plant) science in my perception. But any license would be a plus as compared to no license 🙂

**Comment by CMR248** [comment]
I think we should be cautious with licencing, as many dataset are already deposited somewhere and some might not want to use the licence we propose. If possible I would go for a pop-up-window when turning your ARC public reminding you of choosing a licence. Maybe this is somehing for the DataHUB-Team. 
@j-bauer and @Zerskk : Do you think this is feasible?

**Comment by Zerskk** [comment]
Gitlab has a built-in feature that lets you choose a licence, similar to Github. all a user has to do is click the "add licence" button. Gitlab has predefined templates for this. Should the licence also be specified in Invenio or is it only for Gitlab?

**Comment by j-bauer** [comment]
> I think we should be cautious with licencing, as many dataset are already deposited somewhere and some might not want to use the licence we propose. If possible I would go for a pop-up-window when turning your ARC public reminding you of choosing a licence. Maybe this is somehing for the DataHUB-Team. @j-bauer and @Zerskk : Do you think this is feasible?

InvenioRDM does support adding licenses, tho it is not mandatory (see here: https://inveniordm.docs.cern.ch/reference/metadata/#rights-licenses-0-n). It should probably be a condition to check before a publication can be triggered - that might be part of the CI-Pipeline triggering the whole thing or within the archigator-middleware. That is feasible in any cases.

The "Add license" button within the DataHUB is handy and is definitely a way to add them to ARCs. However the list of available templates is not quite complete - we would need to take a look at whether we can add other licenses to that list. Of course, adding any other license by just creating the LICENSE file containing the text is always an option aswell.

The current ARC template that can be used in the DataHUB to create an initial ARC contains an MIT License - is that still fine or do we want to change it? Or just remove it completely from the template and maybe enforce that the user needs to create one before publication?

**Comment by JonasLukasczyk** [comment]
I would suggest we add to the tree view context menu of directories the item `new text file` which opens a dialog where the user can enter a file name (e.g., README.md) which is then immediately opened in ARCitect's text editor. This way people can easily add readmes and other text files. Regarding the licenses I would not duplicate logic that is already featured on GitLab. If the GitLab UI does not support a specific license I will investigate how to add those.

**Comment by JonasLukasczyk** [comment]
Added in 43add2d89a56d9f5126f84a5a365bb2ca4575dac
