### ISSUE TITLE
[BUG] studies and assays are not registered in isa.investigation file

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#104]
Windows 11
ARCitect v. 0.24

All studies and assays are no longer registered in the isa.investigation file. 
I don't know when this feature was lost, but it is very critical. 
I'm trying to figure out when this happened.

**Comment by Brilator** [comment]
Same on macOS

**Comment by Brilator** [comment]
Works correctly with v0.0.21.

**Comment by Brilator** [comment]
Maybe happened here? @Freymaurer 

https://github.com/nfdi4plants/ARCitect/commit/9d9f43f5e5cc66a15a5258ec86cc1f13635e08ab

**Comment by Freymaurer** [comment]
May i ask why it is critical to display studies and assays in the investigation file?

**Comment by SabrinaZander** [comment]
To my knowledge the isa.investigation.xlsx functions as a registry to the ARC. There you have a summary of each study and assay as well as the metadata containing in them. 

If you have many studies and assays it is very hard to have an overview without this registration in the isa.investigation.xlsx

**Comment by Brilator** [comment]
Ah, I see. This was a design decision on isa xlsx that slipped my attention, right? 
So all studies and assays contained in an ARC are implicitly "registered" without that being written down.

And the study-assay links are only preserved in the respective isa.study.xlsx`s without duplication to the higher level?

**Comment by HLWeil** [comment]
We have been talking about whether this whole registration makes sense in the context of the ARC, where studies and assays have their own place and (as you stated, @Brilator) the registration is just a source of duplication.

But afaik, we haven't made any implementations based on these discussions in ARCtrl yet.

**Comment by Brilator** [comment]
This is still confusing. 

The Swate investigation dialog now shows "RegisteredStudyIdentifiers" for old ARCs (pre light version) only, not for newly created ARCs.

**Comment by JonasLukasczyk** [comment]
I will close this for now as it seems not storing redundant information is the way to go.
