### ISSUE TITLE
[BUG] ARCitect crashed on load

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCitect#106]
This came via helpdesk:

> Did this bug occur right after starting the ARCitect?
> - So yesterday, after creating my ARC, I closed ARCitect to fill the information for SWATE. When I try to open my ARC again because > I want to sync the changes I made, ARCitect is just stuck in the loading screen. So I just turned off my computer and went home. This > morning, when I first opened my computer, I tried to open my ARC from yesterday. It actually worked. Then, I closed it again and see > if ARCitect will be working normally now. However, the issue came back. I tried restarting and shutting down my computer, unfortunately these attempts are not successful to fix this issue.
> 
>    If not, what did you do, that triggered the loading screen?
>    - I only closed and reopened ARCitect again.
>
> Do you have a stable internet connection?
> - yes I have, my univeristy computer is connected via the ethernet.
> 
> Thank you very much and I am really looking forward for this isssue to be fixed. Also, I used the mac version and I didn't encountered this problem. Only here in my office computer which is running Ubuntu 22.04.3 LTS.

I asked for the files producing the crash, will post them as soon as i have them.

**Comment by Freymaurer** [comment]
[TRR_CRC341_B7.tar.gz](https://github.com/nfdi4plants/ARCitect/files/13887611/TRR_CRC341_B7.tar.gz)

**Comment by Brilator** [comment]
Ah, I see. This seems to be related to this error https://github.com/nfdi4plants/ARCtrl/issues/283
After untar 
1. `gunzip isa.investigation.xlsx.gz`
2. Remove the study `SJL-23-03`
3. then the ARC can be opened with ARCitect. 

The isa.study.xlsx of `SJL-23-03` contains four sheets with >1000 rows each and that crashes with the ARCitect.

**Comment by Freymaurer** [comment]
@JonasLukasczyk can you include the latest ARCtrl release? With the performance increase?

**Comment by Freymaurer** [comment]
@JonasLukasczyk @Brilator is this fixed? if yes i should write to the person issueing this via helpdesk.

**Comment by Brilator** [comment]
No. Running ARCitect via `npm start`. 
Package.json lists "@nfdi4plants/arctrl": "^1.0.4"

**Comment by Freymaurer** [comment]
Thanks for the info, i will look into this more in depth

**Comment by Freymaurer** [comment]
So i checked it with a manual read in in ARCtrl and found the following issue: 

![image](https://github.com/nfdi4plants/ARCitect/assets/39732517/60418a07-ab49-4d67-9428-145bf4035b94)

But i am not sure what exactly the issue is, yet. Still investigating. Might be something for @HLWeil when he is back from vacation next monday.

**Comment by HLWeil** [comment]
Just from a quick glance: this is the study parser failing, not the investigaton parser. 

So the investigation file is most probably not the cause for the ARC read in error.

**Comment by HLWeil** [comment]
Looking into it

**Comment by HLWeil** [comment]
The error is the following combination of headers:

![image](https://github.com/nfdi4plants/ARCitect/assets/17880410/17b11cac-8c2b-4c88-ae6d-0d0875d94d85)

Seems like a column was manually deleted, leaving behind two term annotations for one characteristic. Not sure how to handle this. IMO it should definitely fail, but maybe in a more catchable and repairable way?
