### ISSUE TITLE
[BUG] fsmonitor breaks with ARC in network drive

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#107]
We are running into an issue with an ARC stored on a mounted network drive. 
Error message (shown under uncommitted "Changes" in ARCitect):
> Warning: remote repository '//path/to/ARC/on/network/drive' is incompatible with fsmonitor ??

- Changes cannot be committed via ARCitect. 
- `git add .` + `git commit` via CLI shows the same error, but works
- changing the config to via `git config fsmonitor.allowRemote true` did not help
  - now the fsmonitor error is not shown anymore, but changes can still not be committed

 - OS: Windows 10
 - ARCitect v.0.0.24

![fsmonitor-error](https://github.com/nfdi4plants/ARCitect/assets/16229676/cdd4fe08-95fc-4643-8d12-96ecead6bca4)

**Comment by Brilator** [comment]
Cannot reproduce errror on macOS, since there's another issue with that specific file server https://github.com/nfdi4plants/ARCCommander/issues/185

**Comment by JonasLukasczyk** [comment]
I will close this for. Please feel free to reopen if this is still an issue.
