### ISSUE TITLE
[BUG] ARCitect access denied on upload to datahub

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCitect#112]
> Hi, 
when I try to upload changes in my ARC to the DataHUB through ARCitcect I get the error message: "Access denied". Do you have an idea what I am doing wrong? I am using a Linux system (Ubuntu 22.04.3 LTS) and am using the ARCitect v0.0.24. Thanks a lot in advance and best wishes 
Raissa

@JonasLukasczyk @Brilator 

this is a issue on the helpdesk tasks with a request for feedback. The email can be found there. 

Do we need additional information?

**Comment by Brilator** [comment]
ARCitect does not yet ship git binaries for linux. 
I would assume that datahub login then also depends on system settings (git credentials)?

**Comment by Freymaurer** [comment]
> Yes I was logged in with my account in the ARCitect.

> I was trying to upload to the DataPLANT and this is the link of the 
project: https://git.nfdi4plants.org/rkrone/flaveria-rnaseq-raissa.git

**Comment by Brilator** [comment]
Solved for that use case and described here https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/guides/git-troubleshooting.html#access-denied

Will close here, since it's not (only) an ARCitect issue
