### ISSUE TITLE
[Feature Request] add gitconfig with default branch main

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#115]
To avoid issues with ARCitect and ARC commander working in parallel on an ARC, I'd suggest to add `main` as default branch for ARCs. 

If (windows) users simply clicked through git installation (not actively selecting the checkbox to use "main"), the system gitconfig will have "master" as default init branch and this is then also used for ARCs. 

```bash
[init]
        defaultBranch = main
```

**Comment by Brilator** [comment]
not related to #32, which we might also want to change

**Comment by JonasLukasczyk** [comment]
New ARCs created with ARCitect will now use main as the default branch
