### ISSUE TITLE
[BUG] odd ISA behavior (with odd ARC)

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#118]
Just by chance came across an interesting behavior.

At some point I created a script that reads all ISA xlsx files and dumps them as markdowns with same name and structure into a folder at ARC root. 

e.g. `./assays/GCqTOF_targets/isa.assay.xlsx` --> `_isa-md/assays/GCqTOF_targets/isa.assay.xlsx` 
(see https://git.nfdi4plants.org/brilator/Facultative-CAM-in-Talinum) 

In the ARCitect I can now open the assay view from the non-ARC-assay folder `_isa-md/assays/GCqTOF_targets/`. 

Might need to enforce absolute paths for ARC contents.

**Comment by Freymaurer** [comment]
Paths for the ARC are enforced based of arc root. Only the files in ./assays/<assay_name>/isa.assay.xlsx are part of the ARC.

**Comment by Brilator** [comment]
Give it a spin. You can edit the isa.assay.xlsx files from folders not in ./assays/

**Comment by Freymaurer** [comment]
Cannot see the file in the treeview in v0.0.26

![image](https://github.com/nfdi4plants/ARCitect/assets/39732517/884dd7f6-37f7-4be7-9cb4-d451377100c7)

But the `Add Assay` button is definitely a bug.

**Comment by Freymaurer** [comment]
> Try the ARC linked above :) 

I see, i forgot to add the assay folder in my example.

From my understanding, while the assay can be edited with ARCitect. It still is not recognized as part of the ARC. I think this could be an unintended feature. What do you think?

**Comment by Freymaurer** [comment]
Closed for now, feel free to open again.
