### ISSUE TITLE
[Feature Request] add settings menu

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#119]
Might help to store some default settings somewhere, 

- gitconfig #115 
- default "ARC" location #92
- on ARCitect startup
  - open last opened ARC
  - show / hide help menu
  - minimize / maximize sidebar

---

Either stored on system (no need to redo when ARCitect updates, but pollutes) or "inside" ARCitect (would need to move settings from one version to the other)

**Comment by Freymaurer** [comment]
Sadly we can not afford to do this feature request currently. Will close this for now. Might come back later.
