### ISSUE TITLE
[BUG] LFS objects pulled although Use LFS is not checked in Push / pull menu

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#122]
**OS and framework information (please complete the following information):**
 - OS: macOS 14.1
 - ARCitect v0.0.26

**Describe the bug**
- opened existing ARC (previously downloaded without LFS objects {aaa})
- Since download, I added more LFS objects {bbb} to that ARC in the hub from another machine
- went to Versioning - Push / Pull, clicked "Pull" (Use Large File Storage unchecked)
  - LFS objects {aaa} were left out ✅ 
  - LFS objects {bbb} were downloaded ❌

**Comment by JonasLukasczyk** [comment]
We tried this out last time together and it seemed to work as intended. Can you confirm that this bug persists? @Brilator

**Comment by Brilator** [comment]
No sorry, it's not solved. 

- Upload an ARC from machine a using ARCitect. 
- Add a large file e.g. to dataset on machine b using arc commander (it's flagged as LFS in DataHUB)
- I open that ARC on machine a via ARCitect and click Pull with "Use Large File Storage" not selected. And it will pull that large file completely.

**Comment by JonasLukasczyk** [comment]
solved
