### ISSUE TITLE
[BUG] Log not showing

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#124]
Working with ARCitect and ARC Commander in parallel on one specific ARC, I managed to destroy whatever the ARCitect needs to display the git history. Pure `git log` works just fine. The ARC was freshly downloaded from DataHUB 

![Screenshot 2024-01-29 at 12 47 27](https://github.com/nfdi4plants/ARCitect/assets/16229676/2489094f-fb92-492f-9949-0549e49fa42a)

- ARCitect v0.0.26
- macOS 14.2

**Comment by Brilator** [comment]
The ARC in trouble: https://git.nfdi4plants.org/hhu-plant-biochemistry/Samuilov-2018-BOU-PSP

**Comment by JonasLukasczyk** [comment]
The Problem was that the commit messages contained special characters. I added a custom parser that can now handle these special cases.
