### ISSUE TITLE
[Feature Request] Show git warnings more prominently

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#125]
During Versioning --> Push / pull, almost always ends with "Complete". 
Even if warnings, errors, fatal, etc. occur earlier. These are oftentimes lost from focus, i.e. one has to scroll up. However, if users sees "complete" they assume, it all worked fine and are surprised that this is not the case. 

Maybe extract errors and hints and collect them in additional view.

**Comment by JonasLukasczyk** [comment]
I removed the "complete" statement
