### ISSUE TITLE
[Feature Request] rename assay / study

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#127]
Renaming assays and studies by hand is too annoying and error-prone. 
Would be help a lot to support this via right-click context menu on assay/study name.

**Comment by Brilator** [comment]
Just writing down here, how to currently do this by hand in case someone needs it. 

## Rename an assay:
1. rename assay folder
2. rename `Assay File Name` in isa.assay.xlsx
3. rename `Study Assay File Name` in isa.study.xlsx of linked study 

## Rename a study: 
1. rename study folder
2. rename `Study Identifier` in isa.study.xlsx
3. rename `Study File Name` in isa.study.xlsx

**Comment by Freymaurer** [comment]
@HLWeil Can you confirm, that the ARCtrl implementation does handle all points above?

**Comment by Freymaurer** [comment]
This can lead to issues with git lfs files, as change the name of an assay folder will lead to new paths for git lfs files. This must be handled specifically

**Comment by HLWeil** [comment]
Just found a bug when changing a name of an assay which is registered in a study.

**Comment by Freymaurer** [comment]
Done! Will be part of the next release!
