### ISSUE TITLE
[BUG] ARCitect rewrites all isa xlsx

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#129]
Current ARCitect v0.0.26 rewrites **all** isa files, even though just a single study or assay was touched. 
This hampers collaboration, since any work being done in parallel leads to merge conflicts (that are not easily solved on binary files). 

With the light ISA version (studies and assays not being registered in investigation) the amount of changed files would ideally be reduced:
 - change investigation: only isa.investigation.xlsx
 - change study: only that isa.study.xlsx
 - change assay: only that isa.assay.xlsx + the linked isa.study.xlsx

**Comment by Brilator** [comment]
> The behaviour for study and assay should already be correct?

No, ARCitect always writes all isa*xlsx

**Comment by Freymaurer** [comment]
We now have a an API to only get updated file contracts, which should handle this correctly @JonasLukasczyk

**Comment by Freymaurer** [comment]
tracked in #171 will close here
