### ISSUE TITLE
[BUG] SWATE copy functionality errors because of blocked Clipboard library

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/ARCitect#133]
**OS and framework information**
 - OS: [e.g. Windows 11]

**Describe the bug**
- [x] A clear and concise description of what the bug is
When trying to copy single or multiple values  (e.g. by selecting multiple values using Shift) from one row to another using the copy function fromt the context menue I get the following error : "The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details."

- [x] Screenshots
<img width="951" alt="image" src="https://github.com/nfdi4plants/ARCitect/assets/17741807/7cf77c76-7af2-44f4-956f-737d125901aa">

**Comment by JonasLukasczyk** [comment]
fixed
