### ISSUE TITLE
[BUG] Save ARC runs infinitely long when empty Sheet is added to Assay

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/ARCitect#134]
**OS and framework information (please complete the following information):**
 - OS: Windows 11

**Describe the bug**
- [x] A clear and concise description of what the bug is
When the Button "Save ARC" is pressed upon the creation of a new but still empty sheet in a workbook, the save operation seems to be stuck in an infinite loop (see screenshot). Happens for assays and studies.

- [x] Steps to reproduce
1. Create an empty Arc
2. Create an Study 
3. Add an empty worksheet to the Study by pressing "Edit Table" followed by pressing "+" 
4. Click "Save ARC"

- [x] Screenshots
![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/ff028c43-aad6-4a41-8719-20c62a1cd162)

- [x] Expected behavior
- Save an empty table or prompt the user with a warning that the save operation can not be executed for empty tables

- [x] Known workarounds
The loop can be stopped pressing "Window" followed by "Reload", after reopening of your ARC you can add the worksheet again. The save operation will complete successfully when the table is not empty.

**Comment by Freymaurer** [comment]
This is a known issue. Xlsx cannot create empty tables and is already fixed in the newest ARCtrl version (not necessarily fixed, but has a descriptive error)

**Comment by Freymaurer** [comment]
This is implemented in ARCtrl, and runs correctly in Swate 👍 

Will be part of the next release
