### ISSUE TITLE
[BUG] new git logic

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#139]
Tested the current stage: https://github.com/nfdi4plants/ARCitect/commit/705ffe4ccef1f789a70341f8f074275b8e6fc15a
Switching branches and the clear separation into commit // datahub // history is great. 
Just a few things that popped up: 

- [x] #149
- [ ] Commit and history views should be available without datahub-login 
  - fields (name, email) would simply stay blank and could be filled out by hand --> once logged-in, use credentials
- [ ] icon on add brunch is not showing (on macOS)
<img width="286" alt="Screenshot 2024-02-20 at 15 14 27" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/c4b0f34b-c399-4847-bb50-a323869c9f27">

**Comment by JonasLukasczyk** [comment]
We can only enable the History View without datahub login since commits require user data. Mixing datahub user data with local user data is tricky and therefore only enabling datahub user data seems like the best solution.

**Comment by Brilator** [comment]
> Mixing datahub user data with local user data is tricky

Agree. That's why I proposed to leave them blank when not logged-in. This would underline the local-ness of the ARC independent of DataHUB sharing.

**Comment by JonasLukasczyk** [comment]
In the future we can revisit the issue, but currently we want to sync the credentials from the commit view with the push/pull view, so they both require a login. The history view can now be accessed while logged out.
