### ISSUE TITLE
[Feature Request] allow to import "resources" to study

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#140]
There's no real reason why not to allow importing resources.
I would suggest to add the same logic as with "dataset" to allow importing individual files or folders.

**Comment by Freymaurer** [comment]
This was solved by @JonasLukasczyk with an improved context menu (right-click)



![Image](https://github.com/nfdi4plants/ARCitect/assets/39732517/ce2b1f0c-e328-419d-af9a-b90d2d0ec988)

Change will be live with the next release!
