### ISSUE TITLE
[BUG] Access to DataHUB repo denied while being logged in - access token expired?

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/ARCitect#145]
**OS and framework information (please complete the following information):**
e.g. Windows 10, ARCitect v 0.0.27

**Describe the bug**
- [x] A clear and concise description of what the bug is
I tried to push my changes to the remote (nfdi4plants.org) and got my access denied albeit being logged in (see screenshot). Since this ARCommander session was open for a while (> 2hs) I suspect that this issue is related to the token behaviour discussed [here](https://github.com/nfdi4plants/ARCCommander/issues/193)?
- [x] Steps to reproduce

1. open ARCitect, log in
2. wait for longer than 2h
3. try to push to remote 

- [x] Screenshots

![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/fc434174-0939-483a-a19a-b42e11d99a3d)

**Comment by JonasLukasczyk** [comment]
Thank you, #8038904 now automatically refreshes the token
