### ISSUE TITLE
[BUG] spaces in branch name (OK button disabled) 

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#147]
Windows 11, ARCitect version 0.0.27/0.0.28

Including spaces in branch name leads to the message: invalid name (which is good) but  the OK button is disabled so you can't close the window and need to reload ARCitect

![Screenshot 2024-02-22 095714](https://github.com/nfdi4plants/ARCitect/assets/127506066/2fa2bb9b-daba-4878-aa58-986c1c07c54a)

**Comment by SabrinaZander** [comment]
Same is true if you have some errors in switching branches: 

![Screenshot 2024-02-22 100354](https://github.com/nfdi4plants/ARCitect/assets/127506066/98a0ca51-47f6-42da-ac84-700ee59515be)

**Comment by JonasLukasczyk** [comment]
Thank you, this is now fixed #49fab48
