### ISSUE TITLE
[Feature Request] Add preview for .yml files

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/ARCitect#155]
**Is your feature request related to a problem? Please describe.**
Parameters of cwl workflows are specified as .yml files in the runs folder. Currently, they cannot be previewed.

**Describe the solution you'd like**
Add view for yml files 

**Describe alternatives you've considered**
Temporarily use the same view already used for .txt files

**Comment by JonasLukasczyk** [comment]
now supported #682b20d
