### ISSUE TITLE
[BUG] Swate not triggered properly. Issue with cache?

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#156]
Swate dialogs in ARCitect keep showing metadata from different parts (i.e. click an assay, see investigation metadata) or even different ARCs. 

related to #141 ?

**Comment by Freymaurer** [comment]
Can you give some examples? Images?

**Comment by Freymaurer** [comment]
@JonasLukasczyk this seems to be an issue of ARCitect not passing the correct values to Swate? Maybe some bug due to restructuring the file tree view?

**Comment by Freymaurer** [comment]
With v0.0.31 i am unable to reproduce this issue? Could this issue be ARC specific?

**Comment by Brilator** [comment]
It's not ARC-specific, tried with several. But it's also not persistent, sometimes I can smoothly switch between ISA dialogs.

**Comment by Freymaurer** [comment]
This should be solved!
