### ISSUE TITLE
[BUG] freezes on new assay

### ISSUE THREAD

**Issue by eik-dahms** [nfdi4plants/ARCitect#161]
**OS and framework information (please complete the following information):**
 - LINUX

**Describe the bug**
Under certain conditions Arcitect freezes when creating a new assay

**Reproduce**
- click on existing study 
- under registered assay identifiers click + button
- select input field
- now in the file tree click new assay button
- fill fields with previously selected study as study
- create new assay
-> arcitect freezes with loading symbol running 

**Expected behavior**
- no freezing and restarting arcitect

**Ideas for solution**
- exit "new registered assay process" when clicking outside/ leaving study input area

**Comment by Freymaurer** [comment]
Hello! I am sorry for the confusion. We are currently working to improve the handling and make it more error proof! Will update soon!

**Comment by Freymaurer** [comment]
The confusion caused by existing forms should be cleared up with the next release! Should this issue occur again, feel free to reopen 🙂
