### ISSUE TITLE
[BUG] ARCitect file tree not loading when working on attached hard disk

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#162]
When adding assays or protocols to a fresh ARC created on a mounted hard disk, the file tree would not reflect those changes. 

1. Added protocol or assays via ARCitect: visible in Explorer, listed in Commit menu, not visible in ARCitect file tree
2. Reload ARCitect and open same ARC again: now files are visible 

The same is true when adding files via windows explorer: listed in commit menu, not displayed in file tree 

---
- Windows
- ARCitect: v0.0.31
- git (local installation): v2.38

Not related to / not solved by adding hard disk as "safe directory" to git config #114 

Possible reason: 
- delay in hard disk availability / speed

**Comment by Brilator** [comment]
@GuichardM

**Comment by JonasLukasczyk** [comment]
I will close this for now. Please feel free to reopen the issue if it is still relevant.
