### ISSUE TITLE
[BUG] Deleting files does not delete them from the git lfs

### ISSUE THREAD

**Issue by LibraChris** [nfdi4plants/ARCitect#164]
**OS and framework information (please complete the following information):**
- Edition Windows 10 Enterprise
- Version 22H2
- OS build 19045.4046
- Arcitect version 0.0.31

**Describe the bug**
- [ ] When you delete a file and commit this change, this file is not deleted from the lfs tracking
- [ ] This means you cannot delete a lfs tracked file and reupload it without the lfs tracking

**Comment by JonasLukasczyk** [comment]
Fixed
