### ISSUE TITLE
[BUG] ARCitect always adds a Unit column

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#169]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - ARCitect-0.0.31

**Describe the bug**
- I added a characteristic column for organism to my table and selected "Term", to put in "Hordeum vulgare" from NCBITaxon
- After adding, when I expand the table, there is a Unit column, even though there should be none, only TSR and TANs
- while the unit column is empty, it shouldn't be there in the first place

![Screenshot from 2024-03-20 11-37-37](https://github.com/nfdi4plants/ARCitect/assets/108814050/4f4bf3b5-8f26-4cf8-a725-3ea99d044cd6)

**Comment by Freymaurer** [comment]
Is there a unit column in the xlsx when you write it?

**Comment by Freymaurer** [comment]
Due to performance reasons this is the current design, but i habe an issue open on the swate repo.

**Comment by Hannah-Doerpholz** [comment]
I don't think it's a big deal, especially if users are not that familiar with the ISA format. Maybe then they wouldn't even have noticed.
