### ISSUE TITLE
[BUG] ARC not showing up in Downloads View 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#170]
One ARC is not showing up in Downloads View 

https://git.nfdi4plants.org/hhu-plant-biochemistry/Wrobel-2023-CastorBeanEndospermProteome

**Comment by JonasLukasczyk** [comment]
Can you please check again. It appears in my list:

![image](https://github.com/nfdi4plants/ARCitect/assets/24282273/c9fd7216-7e4e-4436-972c-57f24cd96275)

**Comment by Brilator** [comment]
Yes, I can see it now. No idea what the issue was.
