### ISSUE TITLE
[BUG] git init sometimes fails

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#172]
Occurred in some recent workshops. Sometimes the ARC folder is not initialized as a git repo on Linux / Mac. 
ARCitect starts up fine, no git installation failure, but then `git init` is not done. 

Cannot reproduce the error. Seems to depend on system Git installation.

**Comment by Freymaurer** [comment]
How important is this issue? How many times did it occur? For how many people?

**Comment by JonasLukasczyk** [comment]
I think this might have been fixed with our latest updates. Please feel free to reopen if users encounter this again.
