### ISSUE TITLE
[BUG] Saving ARC restores deleted study

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/ARCitect#180]
**OS and framework information (please complete the following information):**
 - Edition: Windows 11 Enterprise
 - Version: 23H2
 - OS build: 22631.3527
 - Arcitect version: 0.0.31

**Describe the bug**
- [ ] When trying to delete a study from within ARCitect and then saving ARC, study reappears
- [ ] Same happens when deleting the actual folder in the ARC manually
- [ ] Not sure if relevant, but ARC is not connected to remote repository yet

**Comment by Freymaurer** [comment]
@JonasLukasczyk this might be solved by just updating ARCtrl to v2.0.0-
