### ISSUE TITLE
Enable upload from network folder

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/ARCitect#181]
**Is your feature request related to a problem? Please describe.**
ARC stored and edited on an network drive. When trying to  commit / upload error occurs:

git checkout tal: detected dubious ownership in repository at '//syno.bio.uni-kl.de/biotech/ARCsyncETC/test/testarc/testarc'
fatal: detected dubious ownership in repository at '//syno.bio.uni-kl.de/biotech/ARCsyncETC/test/testarc/testarc'
'//syno.bio.uni-kl.de/biotech/ARCsyncETC/test/testarc/testarc' is owned by:
'S-1-5-21-1036228674-4065426080-1347446729-74989'
but the current user is:
'S-1-5-21-1788749962-3905053420-4232863692-500'
To add an exception for this directory, call:
git config --global --add safe.directory '%(prefix)///syno.bio.uni-kl.de/biotech/ARCsyncETC/test/testarc/testarc'

**Describe the solution you'd like**
be able to commit and push data from networkdrive, give it the option to be a save directory (last line in error message)

**Describe alternatives you've considered**
same happened as well with ARCcommander, after starting sync error occured, then i executed the git command (the folder added to save directory) and everything worked fine

**Additional context**

**Comment by Brilator** [comment]
Could theoretically be fixed with adding safe directory to gitconfig

**Comment by JonasLukasczyk** [comment]
This is something that needs to be handled outside ARCitect. A git repository on a network drive introduces ambiguities regarding credentials.

**Comment by Brilator** [comment]
> A git repository on a network drive introduces ambiguities regarding credentials.

True, but how to properly handle that outside of ARCitect? 
The design decision was made to ship the git binary; so users without git installed won't be able to adapt that config.

**Comment by JonasLukasczyk** [comment]
I will close this for now because multiple people editing the same repo in a shared file system goes a bit against the intended use of git (in which every user has a local copy). If this is still relevant feel free to reopen the issue and we will find a fix.

**Comment by Brilator** [comment]
Agree that multiple people should collaborate via git / gitlab logic (not on same location on a server). 
But that's not the issue here. Users don't want to share there large files (ARCs) on personal computers, but rather store them directly on a shared NAS (also for additional backups, etc.).

**Comment by Tom-TBT** [comment]
Same issue here. We have about 100 images of 50 GB each currently on a fileserver, that we must upload to the cloud. Copying the images locally first is not an option.

In the meantime, I can try the `git config --global --add safe.directory` workaround.

**Comment by JonasLukasczyk** [comment]
This flag is now set by default 93c5cefb38e5a9ce2389e5f638b36a949ec2897d. Please note that using git on a shared storage can leak git credentials.
