### ISSUE TITLE
[Feature Request] tagging and selective download of LFS files

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#182]
**Is your feature request related to a problem? Please describe.**
1. Currently LFS check box is all or nothing
2. From within ARCitect it is not clear, which files are pointers only

**Describe the solution you'd like**
1. Right-click or other option to selectively pull LFS files
2. Some LFS flag in file-tree or similar and maybe render / preview the pointer file to display file size

**Comment by JonasLukasczyk** [comment]
1951e20885db1f191d29933699814cb004c534c5 adds LFS tags in the tree view.

**Comment by JonasLukasczyk** [comment]
e7aa4134fbd7cd27f860d0716b6b4fc14851022f adds a ctx menu option to download all LFS files of a directory.
