### ISSUE TITLE
[BUG] Commit with long file names silently fails

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/ARCitect#183]
**OS and framework information (please complete the following information):**

 - OS: Edition: Windows 11 Enterprise
 - Version: 23H2
 - OS build: 22631.3527
 - Arcitect version: 0.0.31

**Describe the bug**
- Commit with files stored in deeply nested folder seems to work
  - (files are genome data downloaded from Phytozome and extracted to runs folder during a workflow run)
- When moving to DataHUB Sync it says to commit first
- Back at commit all file changes are still listed so commit probably failed
- Trying `arc sync` on ArcCommander shows that file names are too long
- When moving whole ARC to higher level in Windows commit and sync work with ARCitect
- Would be good to have an error message also in ARCitect for too long file names

**Comment by eik-dahms** [comment]
@JonasLukasczyk @Freymaurer 

could this be a solution? Just set the congfig accordingly if on a windows system

https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows#:~:text=18%20Answers&text=Git%20has%20a%20limit%20of,260%20characters%20for%20a%20filename.

**Comment by Freymaurer** [comment]
Will look into this in a few minutes and come back after 🙂

**Comment by Freymaurer** [comment]
Hey! So for now we added the git terminal view to remove silent fails!



![Image](https://github.com/nfdi4plants/ARCitect/assets/39732517/5e888506-c5f4-48ad-87d5-27da534cf43d)

The issue with long file names still persists but is visible!



![Image](https://github.com/nfdi4plants/ARCitect/assets/39732517/6697566c-c782-4b16-9a6f-eb895656663d)


At the moment, we are undecided on how to approach this. Should we apply settings to git for the user or should we just return a sensible error?

I will close this issue and open a new issue, in which this can be discussed!

**Comment by Freymaurer** [comment]
This change will be live with the next release! Thanks to @JonasLukasczyk for adding the new view.
