### ISSUE TITLE
[Question] Timeframe for upcoming release

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/ARCitect#186]
Is there a timeframe for the upcoming release? Some features like the commit of large amount of files (#163) would be greatly appreciated by many members of the community.

**Comment by Freymaurer** [comment]
Hello David! Version 0.0.32 will be released next Thursday! 

We just started working with a project board, which will soon be publicly visible. Then it will be easy to access the current roadmap 🎉
