### ISSUE TITLE
Need Partial ARC / LFS download of ARCs

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/ARCitect#192]
**Is your feature request related to a problem? Please describe.**
I would like to download just parts (of the LFS-files) of an ARC, this would be handy if i want to re-evaluate just some datasets of an bigger investigation without downloading all (which failed last time most probably due to timing reasons, cannot remember if there was an error message or not)

**Describe the solution you'd like**
possibility to select just some datasets for LFS-download

**Describe alternatives you've considered**
ARC-commander must have this functionality, i guess, if i dig deep into it?
Web-download from ???

**Additional context**

**Comment by frsommer** [comment]
maybe also helpful do add a message like:
your ARCitect downloaded all successfully

since i am not sure if it is still working on something like here:
![image](https://github.com/nfdi4plants/ARCitect/assets/97098130/be94d8b4-8025-46c9-91d7-5a01d3f534ca)

**Comment by JonasLukasczyk** [comment]
Added in 23afe1d. Now users can rightclick lfs files in the tree view and select "Download LFS File".
