### ISSUE TITLE
[BUG] arm releases not working 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#193]
the following releases did not work for me 

- ARCitect-0.0.32-arm64.dmg
- ARCitect-0.0.33-arm64.dmg

**OS and framework information (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - processor: Apple M3

**Comment by Freymaurer** [comment]
Does release v0.0.33 work as intented?

**Comment by Brilator** [comment]
no

**Comment by JonasLukasczyk** [comment]
Can you be more specific about what is not working? Is the app not starting at all?

**Comment by Brilator** [comment]
Sorry. Yes, it's not opening at all. 

<img width="979" alt="Screenshot 2024-06-18 at 08 41 01" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/8ba8dc7b-6655-464f-b0dc-b4572fb1c0e4">

**Comment by Brilator** [comment]
Compiling from source works 

```bash
npm run compile
open dist/ARCitect-0.0.33.dmg
```

**Comment by Freymaurer** [comment]
@Brilator I think there was a new release just now. Please try if the issue has been resolved! 🙂

**Comment by Brilator** [comment]
I did. Issue persists.

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/ARCitect/releases/download/v0.0.35/ARCitect-0.0.35-universal.dmg works on apple silicon

**Comment by JonasLukasczyk** [comment]
fixed in v0.0.35
