### ISSUE TITLE
[BUG] Not all (private) ARCs are displayed

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/ARCitect#20]
**OS and framework information (please complete the following information):**
 - Windows 11

**Describe the bug**
- After login only the latest ARCs are displayed

![image](https://github.com/nfdi4plants/ARCitect/assets/74731649/7ffa4d87-2441-4bbe-a1c1-112cfebb2f44)

**Comment by JonasLukasczyk** [comment]
fixed
