### ISSUE TITLE
[BUG] problems with git and git-lfs binaries with ARCitect version 0.0.35

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#200]
Windows 11
ARCitect version 0.0.35

We are having problems with git and git-lfs when installing ARCitect version 0.0.35 on a new maschine that never have git or ARCitect installed.
Git and git-lfs were not automatically installed when installing ARCitect. After installing git and git-lfs manually we were still having issues with git-lfs. ARCs could only be pushed without large data. An ARC with large data, tracked by LFS failed to push and we get a "git-lfs not found" error.

We now switched back to version 0.0.31 because I knew it was stable and also installed git binaries correctly. 
I have no idea what the problem is and since which version it started. But I wanted to report the issue.

**Comment by JonasLukasczyk** [comment]
@Freymaurer and I tested this we can not reproduce the issue. ARCitect checks on startup if it can communicate with git and git-lfs. If that is not possible ARCitect should show you an error msg. Did you see any error messages? On first startup Windows Defender might ask you to grant permission for ARCitect. Did you see such a request?

Here are two things you can try to debug the issue:
1. Open the Developer Console in ARCitect by pressing `CTRL+SHIFT+i`. In that console you should see the versions of the detected git and git-lfs binaries.
2. Check if in the ARCitect directory has a resources subdirectory that contains the git binaries.

**Comment by JonasLukasczyk** [comment]
This seems no longer relevant. Please feel free to reopen the issue.
