### ISSUE TITLE
[Feature Request] Report when SWATE service is down 

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/ARCitect#206]
**Is your feature request related to a problem? Please describe.**
Currently the SWATE service is down, this is hard to tell for the user as the user is currently facing the following GUI:

<img width="941" alt="image" src="https://github.com/nfdi4plants/ARCitect/assets/17741807/3388ec79-96a6-4a83-b9ed-c41e38dd6a2d">

I think it would be great if the availability could be checked and reported if the service is not available

**Comment by j-bauer** [comment]
As an idea: can't you just evaluate the HTTP return code of the API call? Don't know what they are but something like `!= 200` -> error message ? And in the case of a timeout just wait x seconds for a response and if not, also show an error message.

**Comment by kMutagene** [comment]
@Freymaurer i'd suggest also adding a healthcheck endpoint to the swate backend service, that way we get more diagnostics to display for https://status.nfdi4plants.org/status/dataplant

Obviously, that will still not work when the whole VM is down, but can be used for other things, e.g. when the DB is down but the service is up, etc.

**Comment by kMutagene** [comment]
example for avpr: https://avpr.nfdi4plants.org/_health

**Comment by JonasLukasczyk** [comment]
For now the following message will appear if SWATE is no loaded after 5 seconds:
![image](https://github.com/user-attachments/assets/e1886d8c-9ef4-493e-9b1d-ddbd0e702668)
