### ISSUE TITLE
[BUG] Committing fails when given a full name (> 2 words)

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ARCitect#209]
**OS and framework information:**
 - ARCitect version 0.0.36
 - OS: Windows 11

**Describe the bug**
- After initializing an ARC, I tried to create a commit, with my full name in the "Name" field being three words. Afterwards I clicked the "Commit" button.

  ![image](https://github.com/nfdi4plants/ARCitect/assets/17880410/645fd162-d86f-414f-8384-2a4728c2f6c3)

- The command chain fails before commiting, when setting the name of the commiter.

  ![image](https://github.com/nfdi4plants/ARCitect/assets/17880410/7cd33580-6c1d-402e-babe-0eb963b7bb5f)

 I think the reason for this failing is the missing `"`, which should frame the name:
   ```shell
   git config user.name "Heinrich Lukas Weil"
   ```

----
Edit: I did no fill-out the "Name" field by hand.

**Comment by Brilator** [comment]
How did you manage to edit your Name? Isn't that pre-defined by login and the field non-editable?

**Comment by HLWeil** [comment]
Uhm, yes 😄 
Will edit it in the issue.

**Comment by HLWeil** [comment]
Actually tested it out directly against git. Apparently `2 word names` are correctly interpreted as arguments for the `config` command, even withouth `"`.
For `3 word names`, the `"` are needed. I would suggest to add them in general for increased robustness.

**Comment by JonasLukasczyk** [comment]
fixed in 136157d934d760adc5f5d850fd31a8a6f115df15
