### ISSUE TITLE
[BUG] Download of (private) ARCs does not work

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/ARCitect#21]
**OS and framework information (please complete the following information):**
Windows 11

**Describe the bug**
One of the three things happens:

- Direct error message
- Download takes forever, but nothing really happens
- If "successful", nothing is displayed (see the following picture)

![image](https://github.com/nfdi4plants/ARCitect/assets/74731649/9b9f9ea0-ac8b-4a5d-ae17-c5e9de940d6e)

**Comment by JonasLukasczyk** [comment]
fixed
