### ISSUE TITLE
[BUG] Blank content in assay sheets (for MS data)

### ISSUE THREAD

**Issue by garibayh** [nfdi4plants/ARCitect#213]
**OS and framework information (please complete the following information):**
- Windows 10

**Describe the bug**
- In an ARC that was already working (in previous versions v0.0.31) I cannot open anymore some sheets in my assays. Particularly, this happens in the assays related to MS data. 

- [ ] Steps to reproduce
1.  Open Assay with different sheets in ARCitect; 
![20240709_Assay](https://github.com/nfdi4plants/ARCitect/assets/170522285/7ea1fcb6-e937-49b6-9dd4-1646f4488079)

2. Open Sheet from Assay, that works Ok :) 
![20240709_Assay-CorrectSheet](https://github.com/nfdi4plants/ARCitect/assets/170522285/a8545520-3222-4c8b-80e0-86d78aac1599)

3. Open MS-related sheet that looks empty (but is not empty!) :(
![20240709_Assay-MSSheet](https://github.com/nfdi4plants/ARCitect/assets/170522285/5b8f4615-c9cd-4530-b7a3-adb2cc46a305)

The sheets are completely available in the downloaded isa file: 
![20240709_Assay-MSSheet-IsaFile](https://github.com/nfdi4plants/ARCitect/assets/170522285/2e3f22db-0d3c-4756-8167-c0213c17812d)

- [ ] Expected behavior
To make it work again :)

- [ ] Ideas for solution

**Comment by Freymaurer** [comment]
Hello! Is this ARC publicly available? Can you open the developer console (`Ctrl` + `Shift` + `i`) and keep it open while trying to open the "MS-related sheet" and sent us a screen shot + text of possible logs?

**Comment by garibayh** [comment]
Hello! An error appears in the console when I try to open the blank sheets: 
![20240709_Assay-MSSheet_ConsoleError](https://github.com/nfdi4plants/ARCitect/assets/170522285/51edd7f4-d72e-4dca-8cb2-803bec1d6463)

Received Assay ValidTiming_BuP02_MS from ARCitect!
14index-DJejvIHO.js:108 Error: Match failure: ARCtrl.CompositeCell
    at ore (index-DJejvIHO.js:108:209127)
    at index-DJejvIHO.js:108:216344
    at bF.f (index-DJejvIHO.js:4:15988)
    at bF.GetEnumerator (index-DJejvIHO.js:4:13971)
    at bt (index-DJejvIHO.js:1:1799)
    at So (index-DJejvIHO.js:4:9685)
    at Ae (index-DJejvIHO.js:4:16255)
    at index-DJejvIHO.js:108:215884
    at bF.f (index-DJejvIHO.js:4:15988)
    at bF.GetEnumerator (index-DJejvIHO.js:4:13971)

index-DJejvIHO.js:108 Uncaught Error: Match failure: ARCtrl.CompositeCell
    at ore (index-DJejvIHO.js:108:209127)
    at index-DJejvIHO.js:108:216344
    at bF.f (index-DJejvIHO.js:4:15988)
    at bF.GetEnumerator (index-DJejvIHO.js:4:13971)
    at bt (index-DJejvIHO.js:1:1799)
    at So (index-DJejvIHO.js:4:9685)
    at Ae (index-DJejvIHO.js:4:16255)
    at index-DJejvIHO.js:108:215884
    at bF.f (index-DJejvIHO.js:4:15988)
    at bF.GetEnumerator (index-DJejvIHO.js:4:13971)
ore @ index-DJejvIHO.js:108
(anonymous) @ index-DJejvIHO.js:108
(anonymous) @ index-DJejvIHO.js:4
GetEnumerator @ index-DJejvIHO.js:4
bt @ index-DJejvIHO.js:1
So @ index-DJejvIHO.js:4
Ae @ index-DJejvIHO.js:4
(anonymous) @ index-DJejvIHO.js:108
(anonymous) @ index-DJejvIHO.js:4
GetEnumerator @ index-DJejvIHO.js:4
bt @ index-DJejvIHO.js:1
(anonymous) @ index-DJejvIHO.js:4
System.Collections.IEnumerator.MoveNext @ index-DJejvIHO.js:4
(anonymous) @ index-DJejvIHO.js:4
System.Collections.IEnumerator.MoveNext @ index-DJejvIHO.js:4
(anonymous) @ index-DJejvIHO.js:4
System.Collections.IEnumerator.MoveNext @ index-DJejvIHO.js:4
(anonymous) @ index-DJejvIHO.js:4
System.Collections.IEnumerator.MoveNext @ index-DJejvIHO.js:4
So @ index-DJejvIHO.js:4
Ae @ index-DJejvIHO.js:4
rw @ index-DJejvIHO.js:108
px @ index-DJejvIHO.js:106
l$ @ index-DJejvIHO.js:108
o$ @ index-DJejvIHO.js:108
tJ @ index-DJejvIHO.js:108
S1 @ index-DJejvIHO.js:108
$S @ index-DJejvIHO.js:108
BT @ index-DJejvIHO.js:108
mf @ index-DJejvIHO.js:106
(anonymous) @ index-DJejvIHO.js:108

**Comment by Freymaurer** [comment]
Thank you for sharing the files, i tested the files with the current development version of Swate and they are running. I suspect the error to be related to our implementation work towards the datamap specification.

https://github.com/nfdi4plants/ARC-specification/pull/104

It seems like ARCitect, Swate, ARCtrl are out of sync at the moment for some cases. This will hopefully be fixed soon. Expect the next Swate release tomorrow night. This should resolve your issue! I will close this for now, should it persist over the next few days or you have more questions feel free to reopen 🙂
