### ISSUE TITLE
[BUG] New ARC not working properly

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#214]
When creating a New ARC, the ARC is created but not immediately opened. 
Opening the ARC works and the ARC seems to be intact. 

https://github.com/nfdi4plants/ARCitect/releases/tag/v0.0.37

Similar behavior on macOS and Windows.

**Comment by JonasLukasczyk** [comment]
Fixed in fd2b750963bb2586e437132cf430c7388cced55b
