### ISSUE TITLE
[BUG] ARCitect ≥ v0.0.35 unstable 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#215]
I'm running into some issues opening existing ARCs with ARCitect starting from version 0.0.35. 
- overall slow performance
- having to force quit the app (ARCitect not responding, spinning wheel)
- especially with bigger ARCs

---
on macOS

**Comment by Brilator** [comment]
While writing the issue above, one 400 MB ARC eventually loaded (took minutes).

**Comment by JonasLukasczyk** [comment]
I assume this is related to the version upgrade of ARCtrl.

**Comment by Brilator** [comment]
Update with v0.0.38 on macOS

- Performance when creating a new ARC is a lot better
- Opening existing medium to large ARCs leads to ARCitect not responding

**Comment by JonasLukasczyk** [comment]
Is this still an issue in the latest releases?

**Comment by Brilator** [comment]
Seems to be solved with ARCitect-0.0.40-universal.dmg.
