### ISSUE TITLE
[BUG] Access denied on ARCitect 0.0.37 push/pull

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#218]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04

**Describe the bug**
I logged into the ARCitect without problem, put when I tried to do push or pull actions I got this error: 
```
git branch
* main
git pull origin main --progress
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://git.nfdi4plants.org/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://git.nfdi4plants.org/usadellab/SC_Ontology/'
git lfs pull origin main
```
I know for a fact though that I have a personal access token. The error appears both when I check and uncheck "use LFS".

**Comment by Hannah-Doerpholz** [comment]
As an add-on: I can download ARCs just fine from the DataHUB (more precisely, from our Usadellab group), even though I would have expected the same error there too.

**Comment by JonasLukasczyk** [comment]
Hi Hannah, thank you for bringing this up. I need more details to debug this. On my machine I can pull/push to remotes with and without an access token. My guess is that your credential manager is somehow in conflict with ARCitect. How did you register your access token? Did you add it to the remote with the new functionality? To investigate the issue please perform a fresh download of that ARC and then add a new remote (without a token) for your personal account and try to push there. If that works then please try to push a new branch to the original remote (still without an access token). If you want we can also meet tomorrow in MS teams to debug this interactively.

**Comment by Hannah-Doerpholz** [comment]
Thanks for the hint that my credential manager is the issue. That saved me a lot of time. For some reason I had multiple user.email (email was duplicated) and user.name (had five incorrect additional entries) for that one repo (not sure where they came from but deleting them fixed my issues). I case someone else wants to look at this issue, this is what I did (lines with # are comments, not commands to execute):
```
# navigate into the repo on your local machine
# check the entries for user.name, I got 6 entries here, only the first one was correct and valid
$ git config --get-all user.name
# the --unset-all removed all entries except for the valid first one
$ git config --unset-all user.name
# do the same for email, I got two entries here
$ git config --get-all user.email
$ git config --unset-all user.email
# check again if there is now only one user.name and one user.entry
$ git config --get-all user.name
$ git config --get-all user.email
```

For me that concludes this issue and we could close it.

**Comment by Hannah-Doerpholz** [comment]
I actually checked something again and I noticed that new entries get added to my credentials when I do a push. After I removed all but my original credentials (which are my GitHub credentials), and then performed a push again, new credentials get added (same email, but different user name, it's the user name I have on GitLab/DataHUB). I'm still not sure where the faulty entries came from though, but pushing and pulling seems to work now with two entries in my credential manager for user.name and user.email, one entry being my credentials for GitHub, one entry for GitLab.

**Comment by JonasLukasczyk** [comment]
Thank you for the update. By default ARCitect will add the name/email credentials of the DataHub account. Maybe we should do this only if no credentials exist. We will discuss this in the next meeting. I will close this issue for now.
