### ISSUE TITLE
[Feature Request] default usage of LFS

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#219]
When uploading large files without checking the box use LFS (described here https://github.com/nfdi4plants/ARCitect/issues/189#issuecomment-2210899448), users run into an error 

```
remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
```

If I understood correctly, this was a change in default behavior between earlier versions (ca. until 0.0.31) and now. 

I'd suggest to default to have this box checked. 
If not checked, large files are properly committed (according to set LFS threshold), but then fail to upload.

**Comment by Brilator** [comment]
@Mestizia

**Comment by JonasLukasczyk** [comment]
Since 1d5c64edffa383f3218615da5a47737b23ae43fe LFS is enabled by default.
