### ISSUE TITLE
[Feature Request] more prominent DataHUB button

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#220]
The small magnification glass icon in the "remote" box of datahub sync dialog is apparently not intuitive – users keep searching how to easily see their ARC in the hub. 
I'd suggest to add a "DataHUB" button in the left sidebar.

**Comment by JonasLukasczyk** [comment]
Mh, I think the magnification glass icon is at least the right UI location to put this button. Maybe you can suggest a more suitable icon: https://fonts.google.com/icons

**Comment by Brilator** [comment]
How about captive_portal? 

Still, I'd suggest to make this bigger, more visible. Maybe move into its own box (instead of remote).

**Comment by JonasLukasczyk** [comment]
019e5479d6a5f119edd28400103d0845f25ef6ea replaced the icon. Making it its own button is weird because these links depend on the chosen remote. We could add one button that opens the current remote, but I don't think there is a good location for that button (next to push/pull does not make sense).

**Comment by JonasLukasczyk** [comment]
I will close this issue for now. I think the new icon does the job.
