### ISSUE TITLE
[Bug]: cannot open the "contact us!" button in arcitect for missing ontologies

### ISSUE THREAD

**Issue by Mestizia** [nfdi4plants/ARCitect#221]
### What happened?

Within arcitect, the ' get in "contact" with us!' button does not redirect to the contact form. 

<img width="1033" alt="Screenshot 2024-07-12 at 15 38 48" src="https://github.com/user-attachments/assets/16cae220-a7d0-4f88-acd3-ac265015b111">

Additionally, there should be something on "try advanced search" that by clicking on it, expands the swate right side bar. At the moment is a bit hidden in the UI.

### What did you expect?

I would like to be able to click on "contact" and open the contact page

### Host

Applies to All

### Host Details

arcitect v0.0.37
Swate Release Version [v1.0.0-beta.04](https://github.com/nfdi4plants/Swate/releases)

### Swate version

Swate Release Version v1.0.0-beta.04

**Comment by JonasLukasczyk** [comment]
The problem is the whitelist for external URLs. Please post all URLs that should be whitelisted.

**Comment by Mestizia** [comment]
In this case, this is the URL that I would expect to be able to open. 

https://support.nfdi4plants.org/?topic=Metadata_OntologyUpdate

I don't know if there are more, I will open an issue when I spot another one.

**Comment by JonasLukasczyk** [comment]
Added to whitelist in 630fb3e299178a8a210bdd79875b7c2d31e4c5e3
