### ISSUE TITLE
[BUG] info button in drop-down menu for building blocks is not working

### ISSUE THREAD

**Issue by toriapetrova** [nfdi4plants/ARCitect#222]
- OS: Windows 11

In ARCitect, when creating an isa table there is a drop down menu where the user can choose a building block and at the bottom right there is an info button. However, when clicking or hovering above it nothing happens. I believe it is supposed to give more detailed information about what each building block represents.
![1](https://github.com/user-attachments/assets/99dff25c-d441-4d15-a127-1a11fd893c4d)

**Comment by JonasLukasczyk** [comment]
URL added to whitelist with 9fee742bb6d3e5ec058562814267e9060c4d85a6
