### ISSUE TITLE
[Feature Request] git init non-arc

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#225]
Related to #223, I would suggest to add a "git init" feature. 

Some people might actually build there ARC by hand. Probably an edge case, but might also help with existing (old) ARCs, that for whatever reason are not git repositories.

**Comment by JonasLukasczyk** [comment]
I will add a warning msg when a user opens an ARC without a `.git` folder. The warning box will also have a button to initialize git.

**Comment by JonasLukasczyk** [comment]
solved with a29f7d7e4c67002fec835311cd7e2cff1c34f80e
