### ISSUE TITLE
[Feature Request] Change order of folders

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/ARCitect#227]
**Is your feature request related to a problem? Please describe.** **Describe the solution you'd like**
Some users have found the alphabetic order of folders in ARCitect to be confusing when creating a new ARC and would find it helpful to have them listed in the order they will probably be added: 1. studies 2. assays 3. workflows 4. runs. Not sure if this has been discussed before, I think that would be a good idea.

**Comment by JonasLukasczyk** [comment]
If this request gets more than five thumps up I will add this.

**Comment by JonasLukasczyk** [comment]
added in acb72f986d84b4c825ccdc31767402aa4b78ae10
