### ISSUE TITLE
[BUG] new version icon although no new version is available 

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#233]
Windows 11
ARCitect v.0.0.38

- ARCitect shows the warning that a new version is available although I'm using the lastest version 0.0.38

![Screenshot 2024-07-17 103149](https://github.com/user-attachments/assets/f4316dfa-05f4-45ff-8aa2-35a4a0723dab)

**Comment by Brilator** [comment]
Should probably ignore pre-releases (there is a 0.0.39 pre-release)

**Comment by JonasLukasczyk** [comment]
4a7d753db5db6a0089ddc0916c8770621922c798 excludes draft releases from this version test
