### ISSUE TITLE
[Feature Request] git add for lfs files seems to load endlessly

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCitect#234]
When adding large chunks of lfs files and commiting them, ARCitect runs one git add command for a larger chunk of them. Each lfs file takes quite some time to add. 

Improve this by running git add command for each file. This creates a better sense of progress and makes the method more fool proof.

![image](https://github.com/user-attachments/assets/aa2a1f5f-b965-434f-b8b9-633ed509c728)

**Comment by JonasLukasczyk** [comment]
1e15ebfa5e0e47598456f7c4c124e47e1e32c1d6 adds more progress reporting
