### ISSUE TITLE
[Feature Request] Move toggle help button to "Help sidebar"

### ISSUE THREAD

**Issue by Mestizia** [nfdi4plants/ARCitect#238]
**Is your feature request related to a problem? Please describe.**
It's more intuitive to click somewhere on the help bar to hide it rather than on the opposite side of the UI

**Describe the solution you'd like**
See attached screenshot, I suggest to move the toggle help button on the bottom right side.

**Describe alternatives you've considered**
The button could be placed on both bars.

![image](https://github.com/user-attachments/assets/fb24df00-092a-46be-a377-c17b38900e71)

**Comment by JonasLukasczyk** [comment]
I will add this feature.
