### ISSUE TITLE
[Feature Request] New UI too crowded when opening swate

### ISSUE THREAD

**Issue by Mestizia** [nfdi4plants/ARCitect#239]
**Is your feature request related to a problem? Please describe.**
UI in its current form is too crowded for standard laptop screens (15'') when opening SWATE.
I agree with the decision to have the help menu open by default. However, the UI gets very crowded and hard to navigate as soon as you open SWATE. 

**Describe the solution you'd like**
The default behavior as the user opens swate or an additional panel, should be to reduce the sidebar or have the menu take up less of the screen. 

![image](https://github.com/user-attachments/assets/ea54aeb4-18a0-4822-bbc1-25d0dad8aa6d)

**Comment by JonasLukasczyk** [comment]
@Brilator I think we should disable the help menu by default again.

**Comment by Brilator** [comment]
agreed

**Comment by JonasLukasczyk** [comment]
fixed in 0d4e71bd21df3750fe94ce4e59fb9ec0364c252f
