### ISSUE TITLE
[Feature Request] tooltips instead of help menu 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#240]
related to #239 and #238 

The help menu is currently very static (and honestly ugly). 
Would be ideal not having to update it individually with every added feature / design. 

Is it possible to add optional tooltips that could be toggled on / off? 
Like a "show help" that then activates a bunch of hoverable ❓ on items? 

I saw tooltips on a few things like the LFS box. However, if those were always present, it would again be annoying (at least for large texts, with links, etc.)

**Comment by JonasLukasczyk** [comment]
That is easily doable. I will prepare a template and help you to get started.

**Comment by JonasLukasczyk** [comment]
f051e37d220f1ad416fcdc54eb188d4b07c7acf3 now provides a `a_tooltip` component that can be added to any UI element and is only shown when `show help` is enabled.

**Comment by Brilator** [comment]
Cool. I'd suggest to add two toggles though. `Toggle Help` and `Toggle ToolTips`. At least during switch phase this could make people aware of tooltips. Plus, this way we can still add longer details / context if needed instead.

**Comment by JonasLukasczyk** [comment]
Addressed in #244
