### ISSUE TITLE
[BUG] Changes to tables made outside of ARCitect not properly loaded

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/ARCitect#241]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04
 - ARCitect: v0.0.40

**Describe the bug**
I sometimes need to edit my tables outside of ARCitect (e.g. for batch operations on large numbers of rows, this is not really convenient/doable yet in ARCitect). However, the changes I make outside of ARCitect are only partially detected, more specifically, any added rows are not loaded in ARCitect.

**Steps to reproduce**
- [ ] Create a new ARC
- [ ] Create an assay
- [ ] Add any table template
- [ ] Add some values to the row
- [ ] Save the ARC
- [ ] Open the explorer and edit the isa.assay.xlxs file with an external program (open office in my case, also tested it with excel web)
    - [ ] change the existing values in row 1 
    - [ ] add a new row with some content
- [ ] Restart ARCitect and open the ARC again
- [ ] The changes to the existing row are shown, but the additional row is not displayed

**Comment by Freymaurer** [comment]
Can you share the example file? Then we will look into it 🙂

**Comment by shiltemann** [comment]
@Freymaurer sure, here is the file on OneDrive: https://1drv.ms/f/c/f72c4b5fae1f0d2e/Em7BwphmM5lGg5WPBI_AEJcBDx5NLTMmBsjaQ83kuBUOPw?e=ldIhDS

some more details: I started with 180 lines, one per sample. I have paired-end data so this means 360 files, so I wanted a line per file, so (outside of ARCitect) I duplicated the 180 lines, added filenames, then sorted on first column so each pair of lines from the same sample is shown together. ARCitect now shows me only the first 180 lines of the new sorted file. See both 
the "SRA - submissions" table as the "RNA-Seq" table

**Comment by Mestizia** [comment]
I did some further testing as I felt it was related to https://github.com/nfdi4plants/Swate/issues/474 

That issue refers to macos and windows, the issue in ubuntu is probably connected.

Here is a mock table I created in arcitect (ubuntu):
![Screenshot from 2024-07-19 15-35-20](https://github.com/user-attachments/assets/cd9d392c-829c-458a-86e7-265415b64d0b)

Opening it in open office gives no error, I added some data in open office as you can see:
![Screenshot from 2024-07-19 15-37-45](https://github.com/user-attachments/assets/f4e6c146-dd94-45fd-aaa9-85f14e059196)

After saving and closing office, I open again arcitect and open the table. However, the values in rows that were not created in arcitect still do not show up (6). Additionally, columns where there was no data filled in before are also missing the values (5). Notably, cells for which there were already values in both row and column in arcitect do work (4). Further testing shows that I can successfully edit cells that were already filled in arcitect with open office and the changes will show up in arcitect.
![Screenshot from 2024-07-19 15-39-30](https://github.com/user-attachments/assets/ec2f1510-015e-4983-9387-b52659716797)

**Comment by Freymaurer** [comment]
> @Freymaurer sure, here is the file on OneDrive: https://1drv.ms/f/c/f72c4b5fae1f0d2e/Em7BwphmM5lGg5WPBI_AEJcBDx5NLTMmBsjaQ83kuBUOPw?e=ldIhDS
> 
> some more details: I started with 180 lines, one per sample. I have paired-end data so this means 360 files, so I wanted a line per file, so (outside of ARCitect) I duplicated the 180 lines, added filenames, then sorted on first column so each pair of lines from the same sample is shown together. ARCitect now shows me only the first 180 lines of the new sorted file. See both the "SRA - submissions" table as the "RNA-Seq" table

I do not have permission to access the isa.assay file 😅

**Comment by shiltemann** [comment]
oops, updated, permissions, better now?

**Comment by Freymaurer** [comment]
Yes! And i already found the issue! Swate (and underlying ARCtrl) work based on xlsx tables.

> [!TIP]
> The content of the annotation table MUST be placed in an xlsx table whose name starts with annotationTable. Each sheet MUST contain at most one such annotation table. Only cells inside this table are considered as part of the formatted metadata.
>
> https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#annotation-table-sheets

In your example file the table only spans to row 181. Therefore, ARCtrl ignores everything else.

![image](https://github.com/user-attachments/assets/2433777b-eaf8-47fb-9bcd-a9a33e2d9191)

@Mestizia 

> After saving and closing office, I open again arcitect and open the table. However, the values in rows that were not created in arcitect still do not show up (6).

Can you verifiy if this is the same issue? With the table not spanning row 3?

> Additionally, columns where there was no data filled in before are also missing the values (5).

This is the "Term Source REF" column, which is hidden by default in Swate. Can you expand the composite column by clicking on this icon?

![image](https://github.com/user-attachments/assets/ac871195-2bc6-46f5-ad09-7f88421afeec)

**Comment by shiltemann** [comment]
@Freymaurer thanks for troubleshooting! ok... I learned something new about Excel files today ;P ..and more importantly I can continue with my ARC again, so thanks a bunch for the quick response!

**Comment by Mestizia** [comment]
> Yes! And i already found the issue! Swate (and underlying ARCtrl) work based on xlsx tables.
> 
> Tip
> 
> The content of the annotation table MUST be placed in an xlsx table whose name starts with annotationTable. Each sheet MUST contain at most one such annotation table. Only cells inside this table are considered as part of the formatted metadata.
> 
> https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#annotation-table-sheets
> 
> In your example file the table only spans to row 181. Therefore, ARCtrl ignores everything else.
> 
> ![image](https://private-user-images.githubusercontent.com/39732517/350438038-2433777b-eaf8-47fb-9bcd-a9a33e2d9191.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTgxNTAsIm5iZiI6MTcyMjUxNzg1MCwicGF0aCI6Ii8zOTczMjUxNy8zNTA0MzgwMzgtMjQzMzc3N2ItZWFmOC00N2ZiLTliY2QtYTlhMzNlMmQ5MTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEzMTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MzFlNmI4NTEyNjBhOTExYWIwOTVmYjBlZTQ3OTBlOGQ0M2I1MjdhZWY3ZTEyOGJhNGYxOTdiMTgzZDczMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qxsH8ClF-KVXXEhiQMNBzHPMT9G0jOeZfBC8L1W2wew)
> 
> @Mestizia
> 
> > After saving and closing office, I open again arcitect and open the table. However, the values in rows that were not created in arcitect still do not show up (6).
> 
> Can you verifiy if this is the same issue? With the table not spanning row 3?
> 
> > Additionally, columns where there was no data filled in before are also missing the values (5).
> 
> This is the "Term Source REF" column, which is hidden by default in Swate. Can you expand the composite column by clicking on this icon?
> 
> ![image](https://private-user-images.githubusercontent.com/39732517/350439212-ac871195-2bc6-46f5-ad09-7f88421afeec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTgxNTAsIm5iZiI6MTcyMjUxNzg1MCwicGF0aCI6Ii8zOTczMjUxNy8zNTA0MzkyMTItYWM4NzExOTUtMmJjNi00NmY1LWFkMDktN2Y4ODQyMWFmZWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEzMTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZGIyOGRjMGVlYzljNzIyZGUxZTIyODMyZGY3ZTkyMzRmNWFkMGZlOTY5MTAwZjc5YWVmMDk3NzM2OTNiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nVykD0VQQAMYzB9XgWmWk9Es-K_pmU8L4xQrdqWGrUU)

Yes it is there, sorry for the delay!
That actually means that I can edit the table in libreoffice calc.

**Comment by Freymaurer** [comment]
Awesome! I'll close this issue for now, feel free to reopen!
