### ISSUE TITLE
[BUG] Linking assays to studies

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/ARCitect#243]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04
 - ARCitect: v0.0.40

**Describe the bug**
I was trying to link my assays to a study, but could not figure out how to do it.

In the [documentation](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/guides/arcitect_QuickStart.html#link-your-assay-to-a-study), it is stated to select a study when you create an assay, but this option no longer appears in the new assay dialogue. Furthermore, I created my assays before my study, so I would have needed a way to do this after creation of the assay.

I would have expected a "study" field on the assay's main metadata page/table (or an "assays" field on the study metadata page) where this could be set.

Not sure if this is a bug, or if there is just a different way of doing things now and it's just a matter of updating the documentation to match, but I ran into this issue today and was unsure how to proceed. 

Seems to have changed in ARCitect v0.0.36

**Comment by Freymaurer** [comment]
This is optional. We decided to use implicit references in ARCitect. This means if you use any node from any assay as part of a study, the assay will autoamtically be part of the study. 

This decision is based on merge conflicts on .xlsx files. Picture the following situation. Two people working on one ARC, both add one assay. If the assay is explicitly referenced in the related study file, they will run into merge conflicts. With implicit references only the respective assay.xlsx is updated and the users will encounter no merge conflicts.

**Comment by shiltemann** [comment]
ok cool, makes a lot of sense, and great that it's now autodetected so to speak. 

So by "use any node of an assay as part of a study", do you mean e.g.  referencing the same sample identifiers etc? neat :)

Then perhaps removing/updating the section in the documentation is in order? (happy to move this issue or start a PR if useful)

**Comment by Freymaurer** [comment]
> So by "use any node of an assay as part of a study", do you mean e.g. referencing the same sample identifiers etc? neat :)

Exactly! This follows the specification seen [here](https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#study-file):

![image](https://github.com/user-attachments/assets/a70a848a-7a39-441b-8d2b-84e83d2dee35)

> Then perhaps removing/updating the section in the documentation is in order? (happy to move this issue or start a PR if useful)

Absolutly, currently a lot is happening for Swate and ARCitect and we are not many people, so it is very likely to find outdated information in the docs 😞 Any help (**PR**s or even just notifying us of these **issue**s) is more than welcome!

**Comment by shiltemann** [comment]
ok, will do, and thanks for taking the time to explain things to me!
