### ISSUE TITLE
[BUG] Authentication issue

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#245]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04
 - ARCitect v0.0.40

**Describe the bug**
When I push/pull from standard git in the terminal and later on try to do the same again from within the ARCitect, I always get an authentication error from the ARCitect. This only ever happens if I have done some manual pushes/pulls from the terminal before. I can always resolve it by removing the remote from within the ARCitect and adding it back in again, but this behaviour is a bit curious to me. This might not be an issue though for many people if they never use the terminal anyways, so to me this is very low priority, especially since it can be easily resolved.

**Comment by JonasLukasczyk** [comment]
I can not reproduce this issue. It seems like again your credential manager sets some things up the first time you manually push/pull which conflicts with ARCitect. To debug this I more information. Can you paste the entire output of the git msg box?

**Comment by Hannah-Doerpholz** [comment]
I actually can't reproduce it anymore. I noticed that there are sometimes issues when I do manual actions but that seems to be something from my side and nothing from the ARCitect. Feel free to close this issue.
