### ISSUE TITLE
[Feature Request] Improve personal access token helptext

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#246]
**Is your feature request related to a problem? Please describe.**
When I want to push large files I need a personal access token. Creating that is no problem at all. To me it is just not clear what I have to put into the field in the ARCitect. Should it be the token content or the token name? Also, what rights does that token need? Usually I only ever give read_repository and write_repository permissions. 

**Describe the solution you'd like**
More information about the right access token and what to put into the input field is needed.

**Describe alternatives you've considered**
I can always just use plain git and the terminal to upload my large files with a personal access token if there is no easy solution for this. I don't think this can be expected from users who are not that familiar with git though.

**Comment by Brilator** [comment]
Feel free to contribute to the help text currently under reconstruction in this PR: https://github.com/nfdi4plants/ARCitect/pull/244

e.g. 
- helpt text: https://github.com/nfdi4plants/ARCitect/blob/tooltips/packages/renderer/src/docs/git-sync.vue
- tooltip: https://github.com/nfdi4plants/ARCitect/blob/tooltips/packages/renderer/src/views/GitSyncView.vue

**Comment by Hannah-Doerpholz** [comment]
My problem is that I also don't know what has to go into the personal access token field there and what kind of permissions the token needs. Otherwise I would be happy to contribute to this.

**Comment by Brilator** [comment]
Ah, I see. 
I know that you are supposed to paste a PAT into the field "Personal Access Token (Optional)".
And I guess for upload you'll need a PAT with "write_repository" or "api" rights. And I would recommend to use an expiration date.

**Comment by Hannah-Doerpholz** [comment]
I know we need to past the PAT, but does it have to be the PAT name (my_test_token_for_the_architect) or the PAT content that can only be copied once while creating the token (the generated letter and digit code)?

**Comment by Brilator** [comment]
the latter

**Comment by Brilator** [comment]
I'm on it

**Comment by Brilator** [comment]
done https://github.com/nfdi4plants/ARCitect/pull/244/commits/03ef67e086c16f422faec348fa4612fe226a636a
