### ISSUE TITLE
[Feature Request] Keep highlight on currently active location in file tree

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/ARCitect#247]
**Is your feature request related to a problem? Please describe.**
Sometimes I have multiple assays that are very similar, and want to be able to double check which one I am currently looking at.  

**Describe the solution you'd like**
In the file tree, highlight the table/location I am currently looking at

**Additional context**
For example: I was unsure if I currently had my WGS_longreads or WGS_shortreads assay open in the main window. Would be nice if in the tree on the left the currently opened table/file/folder was higlighted. 

When you first click on an assay it is highlighted in a darker gray, but once you navigate away from the main metadata tab, this highlighting disappears, would be nice if it stayed highlighted:

![arc-highlighting](https://github.com/user-attachments/assets/3d03481e-3e6d-48ad-9699-7f54e7712a47)

**Comment by JonasLukasczyk** [comment]
Added in 0d4e71bd21df3750fe94ce4e59fb9ec0364c252f
