### ISSUE TITLE
[BUG] branches not showing before first commit

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#248]
**OS and framework information (please complete the following information):**
 - OS: macOS
 - ARCitect v0.0.40

**Describe the bug**
- Create a new ARC
- Before any commit: add a new branch `newbranch` in "Commit" dialog
- branch is being created and switched to, but not showing in drop down
- Also, by not committing to `main` first, the default branch now becomes `newbranch`, and `main` disappears. 

- might make sense to auto-commit to `main` during `New ARC`.

**Comment by JonasLukasczyk** [comment]
The reason for this behavior is that git will not correctly list multiple branches with no commits. As a workaround I will add the feature that ARCitect will perform an initial commit when a new ARC is created.

**Comment by JonasLukasczyk** [comment]
fixed in 6ad77c35bf052d0d61284b5c412ab7f2c21075ee
