### ISSUE TITLE
[BUG] Sync ARC is non-functional

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/ARCitect#25]
**OS and framework information (please complete the following information):**
 Windows 11

**Describe the bug**

- When I am not logged in, nothing happens. Maybe there should be a request to log in here. 
- When I am logged in, it just stops loading at some point. Here it would be desirable to get the appropriate link displayed. 
- A browser window opens in the background, but with an incorrect link (see image). The ARC is also not available in the DataHUB. 

![image](https://github.com/nfdi4plants/ARCitect/assets/74731649/3edec32d-0c7b-417d-b95e-56bbcd7ac916)

**Comment by CMR248** [comment]
- Link is correct now
- after sync inform per dialogue

**Comment by JonasLukasczyk** [comment]
fixed
