### ISSUE TITLE
[BUG] Accessing metadata information of "old" ARCs didn't work 

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#252]
- Windows 11
- ARCitect 0.0.40

I have a problem opening metadata information of old ARCs. I can open the ARC with the latest ARCitect version, but accessing metadata does not work when clicking on the name of the investigation, study, or assay. Only the loading bar is shown and nothing else.

I assume this error is due to a different ISA file structure. The ARC was created with version 0.0.24 in November 2023.

Is there a way for non-programmers to make the data compatible again? Since the ARC is huge and contains many files, I don't really want to create a new ARC.

**Comment by Freymaurer** [comment]
Hello! This might be a easy fix. Have a look at our isa-xlsx specification. https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md

My first guess is, a "wrong" name for metadata sheet. Should this be the issue pls open another issue on the swate repo! 

It might alos help to look into the console. You can toggle it by pressing Ctrl + I inside the arcitect and switching to the console tab.

It nothing helps, feel free to ask for more help, then we'll look into this in more detail 🙂

**Comment by SabrinaZander** [comment]
Thanks Kevin for your quick reply. It seems like I chose a bad timepoint. Maybe there were general Swate problems? Now it worked fine. I'll close the issue.
