### ISSUE TITLE
[BUG] Adding protocol as .md in ARCitect

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#258]
Windows 11, ARCitect v.0.0.41

In former version there was the possibility to add new protocols as .md files directly in ARCitect. You could then edit and save them directly in ARCitect.
When I now add a new file in the protocol folder, a new file is added but cannot be edited in ARCitect anymore. 

Steps to reproduce:
1. Add new text file in protocol folder
![Screenshot 2024-09-03 113840](https://github.com/user-attachments/assets/5aa3b752-b88c-46a2-a08b-0dc2c4d4d5a5)
2. the file "new text file via ARCitect" cannot be edited
![Screenshot 2024-09-03 113919](https://github.com/user-attachments/assets/274d11d5-bfd1-4992-b063-3c392a8fdb35)
3. Only .md files which are created without ARCitect (protocol.md) can still be edited in the Editor. 

Solution:
It would be good to create .md files which can be edited and previewed in the Editor.

**Comment by JonasLukasczyk** [comment]
I can not reproduce the issue. Can you confirm that the following does not work on your machine:
1. In any directory inside the ARC open the context menu and click on 'new text file'
2. Enter 'test.md'
3. Click on the new file and edit it in ARCitect

**Comment by JonasLukasczyk** [comment]
I think you created a file name without an extension. This is why ARCitect does not know that it can edit it. I know it seems reasonable to add a default extension if the user does not provide one, but even if we would do that I would argue for `.txt` and not `.md`.

**Comment by SabrinaZander** [comment]
Thanks for the clarification. I didn't realize I needed to use a file extension. I think in one of the previous versions of ARCitect it was automatically a .md file.
It would be a good option to add a default extension, even .txt is fine for me.

**Comment by JonasLukasczyk** [comment]
ca2e642f7db0d076cba8f16780d6a8bf9043de12 adds the `.txt` file extension if the specified name does not already includes an extension. We can also change this to `.md` in the future if people prefer.
