### ISSUE TITLE
[BUG] Editing of the assay metadata regarding the study not possible.

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/ARCitect#26]
**OS and framework information (please complete the following information):**
Windows 11

**Describe the bug**
When processing the assay, the previously specified Study is not preselected.
Moreover, I cannot select any other study.

**Comment by CMR248** [comment]
![image](https://github.com/nfdi4plants/ARCitect/assets/74731649/a81a6c25-f97b-4f19-8f83-abbfb92e7bdd)

**Comment by JonasLukasczyk** [comment]
Solved
