### ISSUE TITLE
[BUG] ARCitect remote accounts not showing up

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#261]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04
  
**Describe the bug**
Today a colleague noticed that in the ARCitect when you want to add a remote, we don't see our institute's group and subgroup anymore (usadellab and the szymanskilab), but a lot of other groups (shown in the screenshot below). Previously, our groups could be selected in the "DataHUB account" field, but not anymore. Is there a reason for why this changed? Is it supposed to be like this? It seems like we can still push to the groups by manually changing the remote URL, but it is a bit inconvenient for new users.

![grafik](https://github.com/user-attachments/assets/9cb17aa0-9b3f-4fe4-8993-41897fb65944)

**Comment by JonasLukasczyk** [comment]
Hi, thank you for posting this. Seems like the GitLab API is truncating the list of accounts (now that there are so many ;-)). I will fix this.

**Comment by JonasLukasczyk** [comment]
Fixed in 01be091009096d05f2dfe33992ad3e54893bfe0b
