### ISSUE TITLE
[BUG] unpacker error

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#262]
A windows user got the following error: 

```
error: remote unpack failed: index-pack abnormal exit
To https://git.nfdi4plants.org/user/ARC.git
! [remote rejected] main -> main (unpacker error)
error: failed to push some refs to 'https://git.nfdi4plants.org/user/ARC.git'
```

Did anyone see this before?
Probably more of a DataHUB rather than ARCitect issue. 
@j-bauer

**Comment by Brilator** [comment]
this was pseudonymized on purpose...

**Comment by j-bauer** [comment]
Ok, nevermind then :D I will check the logs...

**Comment by Brilator** [comment]
I guess you won't want to parse every possible error. 

I'd rather suggest to try and avoid having users run into this at all #264. Would require more communication between the tool devs though (limit was not changed to 100 MB).

**Comment by j-bauer** [comment]
@Brilator typo? `not = now`? The limit was changed afaik.

**Comment by Brilator** [comment]
yes

**Comment by JonasLukasczyk** [comment]
This issue will be closed because it is essentially a duplicate of #264
