### ISSUE TITLE
[Feature Request] Information banner for DataHUB downtime

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#265]
It would be great to have the same information banner (or something similar) that shows up on the DataHUB website to also be visible in the ARCitect to let users know if there is a specific time when the DataHUB will be down. Since scheduled downtimes are usually during the weekends and in our group we usually try to do larger pushes during the weekend too, this information would be helpful.

**Comment by j-bauer** [comment]
The recent downtimes during the weekend were not planned. There were some cloud problems once again. The cloud admins are about to deploy a long-term fix. Hopefully the sporadic downtimes will stop then. Sorry for the inconveniences.

For regular maintenance downtime we announce them a couple of days/a week early to inform users as soon as possible.

**Comment by JonasLukasczyk** [comment]
It makes total sense to mirror that banner in the ARCitect. I will implement this.

**Comment by JonasLukasczyk** [comment]
b82d8b767714fff08145d267387a6f9d9a75fbbb introduces a new `Status View`:

![image](https://github.com/user-attachments/assets/3c1f3a9a-1caa-4c72-879f-4244b09c781f)

For now this view displays the banners of the DataHubs that for instance announce downtimes. Downtimes are also highlighted with a red icon. If any hub announces a downtime, then the icon of the status view turns into a warning symbol to indicate that there are messages the user should look at.

Note: it became apparent that many banners are outdated and should be removed from the hub maintainers.

**Comment by Hannah-Doerpholz** [comment]
Awesome, looks great!
