### ISSUE TITLE
[Feature Request] open ARC in CLI

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#266]
Might sound a bit counter-intuitive, but it would help to have a button in the left sidebar to open the ARC on a command line (terminal, windows shell, cmd) with Git and Git-LFS binaries shipped with ARCitect added to temporary path for that cli window.

This would give git-knowledgeable data stewards an easier way to troubleshoot and help with issues that may easily be solved there. 
- No need to know or tell users how to CLI-navigate to ARC folder.
- No need to install Git and Git-LFS (except linux, but given). 
- Could even be easy enough to share single-liners with users

**Comment by JonasLukasczyk** [comment]
285843b2917dfa73670fdda52d4c3d9bc70f5ea5 adds the new category `Tools` to the titlebar which provides options to open the current ARC in the `terminal` and `VSCode`. This needs to be further tested since this is highly platform dependent.
