### ISSUE TITLE
[BUG] Markdown view does not show images

### ISSUE THREAD

**Issue by Mestizia** [nfdi4plants/ARCitect#267]
**OS and framework information (please complete the following information):**
 - OS: MacOS

**Describe the bug**
The readme preview on arcidect does not show image preview 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/21d81e40-3d63-4b5d-bb9b-3d8ba76e5023">
While it does show correctly on git
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/14547833-e0c1-4e3a-bf54-cf988e2af0db">

Is there something that can be done for arcitect to render the image in the preview? 
I will also add that this has low priority from my side.

**Comment by JonasLukasczyk** [comment]
This is an electron linking/packaging issue. I will work on a fix.

**Comment by JonasLukasczyk** [comment]
Now supported since a0b7e1a2fe7219876babe9b681926d5df98e15ef
