### ISSUE TITLE
[Feature Request] Renaming procedure

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#268]
It would be helpful to display the name of the current assay/study you want to rename in the rename field already. Sometimes you only want to change a typo or number. Then it can be tideous to write the whole name again, if it is very long. 

Not high priority, but nice to have :-)

**Comment by JonasLukasczyk** [comment]
Thank you, now featured in 700cdfa37f4fc4a449cd781d0287b07669a37357
