### ISSUE TITLE
[BUG] Cannot push changes with latest 0.043 ARCitect release 

### ISSUE THREAD

**Issue by Mestizia** [nfdi4plants/ARCitect#271]
**OS and framework information (please complete the following information):**
 - OS: Windows, MacOS

**Describe the bug**
- I cannot push ARCs with the latest ARCitect release 0.0.43. It just gets stuck in this state (see screenshot)
- Create an arc, commit and try to push
![image (2)](https://github.com/user-attachments/assets/a58a75ef-d7a5-47e7-81ec-582f5668a8c7)

- I tested 0.0.42 and 0.0.41 and they work. I could replicate it on Windows and MacOS. I am not sure if any behavior changed but I could not commit just after creating the ARC with 0.0.43 but only after adding files/studies etc (I understand it may be a design decision).

**Comment by ZimmerD** [comment]
I also encounter this problem

**Comment by JonasLukasczyk** [comment]
Thank you for catching this. I fixed the issue here 453cda30ea514b969e11daf9080b8086035a7cd2 and I will create a new release.
