### ISSUE TITLE
[Feature Request] datahub communication, receive feedback to update version

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#274]
Since some of the recent sync issues (e.g. LFS) may be related to outdated ARCitect versions, it would help to communicate the ARCitect version being used during push with the DataHUB, which could then trigger a warning / recommendation to update ARCitect. 

@tetraw
@j-bauer

**Comment by JonasLukasczyk** [comment]
Not sure about that. We already display a warning if one uses an outdated ARCitect version in the bottom left corner. I think adding more checks at other locations is just overhead / code bloat.

**Comment by JonasLukasczyk** [comment]
I will close this for now
