### ISSUE TITLE
[Feature Request] extend git logging

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#275]
To allow more trouble shooting, it would help to have more logs from communication with DataHUB. 
Something like achieved via CLI with 

```
export GIT_TRACE=1
export GIT_CURL_VERBOSE=1
```

Since these create rather lengthy logs, I would suggest not to print them as default, but only by user selection.

**Comment by JonasLukasczyk** [comment]
We can add a `Verbose Logging` toggle button to the git views. When on these flags will be set.
