### ISSUE TITLE
[BUG] Private repos are displayed

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/ARCitect#28]
**OS and framework information (please complete the following information):**
Windows 11

**Describe the bug**

- Although I am not logged in, private ARCs are displayed. 
- I was logged in before, clicked "Force Reload" to stop the download of an ARC from DataHUB. After that I was shown private repos.

![image](https://github.com/nfdi4plants/ARCitect/assets/74731649/144402f6-7e1a-487d-9679-6a4e1272e0f2)

**Comment by Brilator** [comment]
No worries, the ones you're showing here are not private. 
Just log out from DataHub and check again.

**Comment by Brilator** [comment]
Ah wait, you're referring to your FruehlingsARC?

**Comment by CMR248** [comment]
Exactly

**Comment by JonasLukasczyk** [comment]
fixed
