### ISSUE TITLE
[Feature Request] Settings view

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCitect#280]
- [x] choose Swate source
 - [x] move toggle help
 - [x] move toggle tooltips
 - [x] store information in config file
 - [ ] Add "Delete ARCitect data" option in settings

**Comment by Brilator** [comment]
add `git lfs` lines to config file

#282

**Comment by JonasLukasczyk** [comment]
There is now a `Reset` option that deletes all local files, but Electron/ARCitect will  shortly after populate that folder again. I would close this for now. In the future we could force electron to only write to a temporary location and make the settings files optional.
