### ISSUE TITLE
[Feature Request] check for / initiate git-lfs

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#282]
Not having git-lfs initiated created a bunch of issues (#264). 

https://github.com/orgs/nfdi4plants/discussions/6

ARCitect should check, whether git-lfs is installed properly or run `git lfs install`.

**Comment by JonasLukasczyk** [comment]
Added in 4d2da7166d285415ef04566ec95c1b8855ea5fcb
