### ISSUE TITLE
[Feature Request] enable to enter sync message and get overview of changes

### ISSUE THREAD

**Issue by eik-dahms** [nfdi4plants/ARCitect#29]
**Is your feature request related to a problem? Please describe.**
- [ ] Before syncing one should be able to write a sync message. Otherwise every commit will be "Update"
- [ ] show changes in ARC to user

**Describe the solution you'd like**
Pop up window or frame in window that lists all changes that have bee applied to the local ARC and a sync message text input field.

**Additional context**
I think the sync message is an inportant part of the ARC strukture/ metadata. One should be able to modify it. 
Also showing the user what has been changed and asking them if they really want to sync might prevent accidental erroneous syncing.

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/ARCitect/commit/9e45bdf25f040916c6c744f483536646f1247a6f
