### ISSUE TITLE
[BUG] Change username

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/ARCitect#290]
I am trying to commit changes via ARCitect 0.0.48

When Committing Changes

I get the following error, 

git config user.name "<redacted>"
warning: user.name has multiple values
error: cannot overwrite multiple values with a single value
Use a regexp, --add or --replace-all to change user.name.

Were can I change the user name?

(Ticket via helpdesk)

**Comment by JonasLukasczyk** [comment]
I can not reproduce this issue. All git commands inside ARCitect are driven based on the user credentials of the DataHub account, and here it seems the user name is not even specified. Please provide more information:
* OS
* which DataHub account
* did the user use the shipped git instance or does the user have a system-wide git instance

**Comment by SabrinaZander** [comment]
I also had the same error with multiple users over the last few weeks.
There was more than one user in the ARC folder's Git configuration.
We replaced the multiple user with `git config --global --replace-all user.name "username".`

They are all using Windows and using the shipped git version.
I feel like this happens sometimes when using new ARCitect version on "old" ARCs but I have no idea why.

**Comment by JonasLukasczyk** [comment]
Fixed in 535bd01b1afdcbe8e46cd6578fc037c487c05889. Will be available in v0.0.52
