### ISSUE TITLE
[BUG] LFS files with space in filenames

### ISSUE THREAD

**Issue by subasini-csb** [nfdi4plants/ARCitect#292]
**OS and framework information:**
 - OS: Windows 11
 - ARCitect version: v0.0.48

**Describe the bug**
- In the ARCitect I right clicked on a folder name and selected download LFS files. Files without space in the filenames were downloaded. The files _**with**_ space threw errors as shown in the example below

 ```git lfs pull --include assays/newControlData/dataset/new_labeling/240725_mtmEOS44_40X_TS3_1h_C_cell_moved to the front.lsm Invalid remote name "to": invalid remote name: "D:\\Users\\mitoseg\\to"```
 
![image](https://github.com/user-attachments/assets/a5889e11-6781-4282-937e-98c0a7eb0a3d)

- [ ] Ideas for solution
- I was able to download when I tried  the following from the root folder in terminal
 ``` git lfs pull --include="assays/newControlData/dataset/new_labeling/240725_mtmEOS44_40X_TS3_1h_C_cell_moved to the front.lsm"```

**Comment by HLWeil** [comment]
I think the reason this does work with the explicit call of `git lfs pull`, but not with the ARCitect might have something to do with the exclamation marks `"`.
Does ARCitect omit them by default, @JonasLukasczyk?

**Comment by JonasLukasczyk** [comment]
Fixed in 6d8099bbb524868d2a7f7a0d15ab989d44d80df7
