### ISSUE TITLE
[BUG] Maybe Bug? New Assay does not ask for study affiliation

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/ARCitect#293]
OS win10, arcitect 00.48
 - OS: [e.g. Windows 10]

**Describe the bug**
- [ ] When i have 2 studies and add a new assay, arcitect does not ask for the study to associate it to.
is this intentional?
when i look in the study isa the new assay is not listed there. but the assay placeholders in the study isa are still there.
- [ ] see above
- [ ] ![image](https://github.com/user-attachments/assets/44cde430-8ded-41bb-b68b-7b8347cdb9d9)
- [ ] ask for assay name and for study to associate
- [ ] Ideas for solution

**Comment by JonasLukasczyk** [comment]
We recently made the design decision to track the links between Assays and Studies implicitly based on the stored processes instead of explicitly specifying the correspondences. So this behavior is expected.

**Comment by Mestizia** [comment]
@frsommer If you have opinions on the subject, share them here: https://github.com/orgs/nfdi4plants/discussions/4
