### ISSUE TITLE
Add install instruction

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#3]
When we tried installing the ARCitect we noticed that after installing npm, we also had to install nodejs as well. That should be added to the readme as install dependencies.

**Comment by Brilator** [comment]
Just write a pull request ;)

**Comment by Brilator** [comment]
In the long run, this repo and README will just be for us. Jonas is working on packaging the tool, so that users do not have to install node.js and packages.
