### ISSUE TITLE
[Feature Request] Swate save --> save ARC button 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#302]
After some [swate performance improvements](https://github.com/nfdi4plants/Swate/releases/tag/v1.0.0-beta.17), users now have to click "save" twice when interacting with Swate view / Annotation tables:
1. Click on Save inside swate (top-left)
2. Click in `Save ARC` in sidebar

I'd suggest to have 1. trigger 2. 
To my understanding this would make the sidebar button obsolete.

**Comment by JonasLukasczyk** [comment]
Having two buttons is really unnecessary. I know the second button was introduced to cope with a performance issue in SWATE which prohibited realtime serialization of the modified ARCs. So users now have to manually trigger this "long" save process. In fact this is a bigger design problem now. Previously, users edited Investigations/Studies/Assays and then the modified versions were immediately send back to ARCitect which then stored them to disk only after users pressed the save button. So the only way to lose work was to make changes with SWATE and then close ARCitect before pressing the save button. Now there are even two ways users can lose work.

What about this solution:
* we remove the save button from ARCitect
* when the save button in SWATE is pressed then ARCitect also saves the ARC to disk
* if users click on another I/S/A file in ARCitect while they have unsaved changes in SWATE they should see a confirmation dialog warning them that they could lose work

For the last part @Freymaurer and I will at least have to communicate a 'modified' flag between ARCitect and SWATE.

**Comment by Freymaurer** [comment]
I also thought about your second suggestion which should feel the most natural. Maybe both save Buttons should save current progress in Swate to disc. But having the ARCitect button do this will require a new communication path. 

As this is only a temporäre fix, i suggest going for the second option for now. Save button in swate should also save to disc. Anything else will be done after evaluation.

**Comment by JonasLukasczyk** [comment]
now a SWATE save will trigger an ARCitect save. Since there is no need to manually save an ARC without SWATE I removed the save button from ARCitect. In the future the user should get a warning if changes were made that would be lost when the user changes to a different I/S/A file.
