### ISSUE TITLE
[BUG] lfs time out error with single very large files 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#304]
The implemented PAT workaround works well to avoid time out errors for large-size pushes. 
However, ARCitect still runs into time outs if single files take very long to upload. 

Deactivating the lfs activity timeout helped: 

```bash
git config lfs.activitytimeout 0
```

I'd suggest to implement this in ARCitect as well.

**Comment by JonasLukasczyk** [comment]
added in v0.0.51
