### ISSUE TITLE
[BUG] commit error library

### ISSUE THREAD

**Issue by JinyiZhu1** [nfdi4plants/ARCitect#308]
**OS and framework information (please complete the following information):**
 - OS:  Windows 10

**Describe the bug**
I have created an ARC in the past, I want to make changes, but I got an error during the sync. 
![image](https://github.com/user-attachments/assets/0b709d47-367a-46a2-b95c-17331a849de9)

**Comment by Brilator** [comment]
Please see this related issue https://github.com/nfdi4plants/ARCitect/issues/132

**Comment by JinyiZhu1** [comment]
Small update: 
I don't know if it helps but I managed to push using an older version of Arcitect (0.31) that I still had on my laptop.

**Comment by Brilator** [comment]
Thanks. 
Is this the same laptop from where you tried pushing with the other version?

**Comment by JinyiZhu1** [comment]
Yes. the same laptop.
