### ISSUE TITLE
[Feature Request] change remote

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#31]
Would help to be able to adapt the remote

1. Adapt to re-route to a new remote
2. be able to choose available groups or namespaces

<img width="1017" alt="Screenshot 2023-07-12 at 18 15 41" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/a5764889-54b2-4624-b06d-3da644207a63">

**Comment by Brilator** [comment]
Use-case: 

1. User creates ARC (defaults to user namespace) 
2. User transfers ARC to another gitlab group (e.g. lab group)
3. Cannot sync to group-shared ARC / ARCitect defaults to user namespace. 

#56

**Comment by andreaschrader** [comment]
Same for me when opening an existing ARC from a group, changing something and uploading again, a new ARC under my name is created. 
This can quickly lead to work on two different ARCs assuming these are the same.
Moreover it appears that the person wanting to contribute to this ARC is suddenly the only owner of an ARC which was before intentionally placed in a specific group.

**Comment by Freymaurer** [comment]
Solved since v0.0.24! :sparkles: by @JonasLukasczyk 🎉

**Comment by Brilator** [comment]
I don't think it is. v0.0.24 can handle download from selectable hosts (i.e. gitlab instances). 
But the remote url in the versions tab defaults to (overrides) `host/<userName>/<arcName>`.

**Comment by Freymaurer** [comment]
I am very sorry i confused this issue with the select datahub issue

**Comment by JonasLukasczyk** [comment]
Added in #102
