### ISSUE TITLE
[BUG] dead link to DataHUB personal access token in commit view 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#315]
Apparently, the user settings in DataHUB have moved

Was: https://git.nfdi4plants.org/-/profile/personal_access_tokens (ARCitect redirects here)
Is: https://git.nfdi4plants.org/-/user_settings/personal_access_tokens

**Comment by JonasLukasczyk** [comment]
Fixed in 222733dee7bd8bcb0d394b8650209fccc264bb11
