### ISSUE TITLE
[BUG] Side bar and help differ.

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/ARCitect#33]
**OS and framework information (please complete the following information):**
 - macOS Ventura 13.4.1

**Describe the bug**
- [x] A clear and concise description of what the bug is
   > Sidebar on the left and help on the right differ, "Versions" vs "Synchronize ARC". 
- [x] Steps to reproduce
   > Open the ARCitect according to the instructions in the GitHub repo for a cloned repo.
- [x] Screenshots
   > <img width="1440" alt="Screenshort_ARCitect_GUI_synchronize" src="https://github.com/nfdi4plants/ARCitect/assets/85687301/257e8076-2d73-4ebf-9b0f-e29cebda28b8">

- [x] Expected behavior
   > Synchronize ARC" instead of "Versions" in the sidebar
- [x] Ideas for solution
   > either "Versions" on the right hand help point (9) or "Synchronize ARC" in the sidebar

**Comment by Brilator** [comment]
Done #35
