### ISSUE TITLE
[Feature Request] support for copy / paste by keyboard shortcut on macOS

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#37]
Some menus don't allow to paste to (e.g. creating file names, identifiers) / copy from (e.g. remote url)

**Comment by Freymaurer** [comment]
Can you specify which ones?

**Comment by Brilator** [comment]
This relates to an early version and under macOS only. 
Copy/paste is now supported although without support for shortcuts. 
Changed the title accordingly.
