### ISSUE TITLE
[BUG] Markdown editor grey box 

### ISSUE THREAD

**Issue by setri100** [nfdi4plants/ARCitect#38]
When the left help bar is on, the markdown editor is obscured by the grey bar on the right. See image attached 

<img width="1273" alt="Bildschirm­foto 2023-08-16 um 13 45 35" src="https://github.com/nfdi4plants/ARCitect/assets/60262318/60c3d1ea-6737-4e40-bf66-56beabdc955b">

**Comment by JonasLukasczyk** [comment]
@setri100 please check if this problem still exists with the latest release. Also which os are you using?
