### ISSUE TITLE
[BUG] Opening an ARC sometimes doesn't work

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#42]
**OS and framework information (please complete the following information):**
 - OS: Windows 11 Pro
 - Using ARCitect 0.0.5

**Describe the bug**
-  A clear and concise description of what the bug is: 
When I want to open an ARC, the loading wheel spins for a very long time. With some ARCs, it spins until you close the application or reload it. ARC will not open. You don't know if something is happening in the background. 

-  Steps to reproduce
Open ARCitect, click on Open ARC

- Screenshots
![Screenshot 2023-08-25 100715](https://github.com/nfdi4plants/ARCitect/assets/127506066/8acc3814-b2c8-419c-b63b-da9396d884be)

- Expected behavior
ARC is opened

- Ideas for solution
Add a loading bar so you know something is happening in the background. Possibly problems opening ARCs created with ARC Commander/old ARCitect versions? Has to be checked.

**Comment by SabrinaZander** [comment]
Hi Jonas,

I invited you to an ARC causing the crash. This arc was created with the ARC Commander. I have more ARCs which causes crashes. Also only demo ARCs without any data. But unfortunatly I can't upload them to the DataHub because I have some troubles with the access token in the ARC Commander. I'm working on this problem and can hopefully give you more examples. 

An error message would be great :-)

**Comment by andreaschrader** [comment]
> ... But unfortunatly I can't upload them to the DataHub because I have some troubles with the access token in the ARC Commander. I'm working on this problem and can hopefully give you more examples. ...

Hi Sabrina,
maybe [this](https://github.com/nfdi4plants/arcCommander/discussions/157) or [this](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/faqs/faqs.html#arc-commander) (How to retrieve a valid access token?) helps with respect to the access token?
😄
