### ISSUE TITLE
[Feature Request] LFS large file download

### ISSUE THREAD

**Issue by muehlhaus** [nfdi4plants/ARCitect#44]
**Is your feature request related to a problem? Please describe.**
Toggle between LFS large file download and pointer file download

**Describe the solution you'd like**
ARC download with large files 
and ARC download without large files (pointer only)

Default Large File Download off.

**Comment by Brilator** [comment]
Feature is enabled in v0.0.8. 

However, I'm running into an issue with a larger ARC (25 GB).

<img width="400" alt="Screenshot 2023-09-20 at 09 01 47" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/1ea6a7d2-0d99-44e7-bfd2-c08242e5fbf7">

Independent whether I check / uncheck the LFS box, I get this error: 

<img width="400" alt="Screenshot 2023-09-20 at 08 59 49" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/2fbbc748-eebb-420f-9b6d-91c1cd4664b4">

And the ARC is only downloaded partially: 

<img width="300" alt="Screenshot 2023-09-20 at 08 59 59" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/281389ab-dc11-4e60-981b-681de6f1cd5f">



I don not get this error with pure git (git clone https://git.nfdi4plants.org/brilator/samplearc_rnaseq.git)

**Comment by JonasLukasczyk** [comment]
I can not reproduce this issue. @Brilator Can you please check if this problem still persists with the latest version? Are you running this on MacOS or Windows?

**Comment by Brilator** [comment]
LFS download (with and without LFS objects) seems to work with the latest version (built from source on macOS just now). 

Tested on a different ARC, since the ARC linked above is not listed anymore in the ARCitect downloads.

**Comment by JonasLukasczyk** [comment]
That is strange. I tested this with the ARC shown above "Facultative-CAM-in-Talinum". You can not see that repository anymore? This could be another bug.

**Comment by Brilator** [comment]
Yes, but probably one that is not ARCitect-related. It's just one of the oldest ARCs and carries a bunch of old artifacts (validation also does not work).

**Comment by Brilator** [comment]
Works with v.0.020 on macOS when using the git-lfs workaround. 

https://github.com/nfdi4plants/ARCitect/discussions/88
