### ISSUE TITLE
[BUG] Set of publication status crashed ARCitect

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#45]
**OS and framework information (please complete the following information):**
 OS: Windows 11 Pro
Using ARCitect 0.0.5

**Describe the bug**
When you want to set a Status of a Publication (doesn't matter which one you select) and click the  "add publication" button the ARCItect crashed. By crashed I mean the loading wheel spins forever until you close or reload the application. 

![Screenshot 2023-09-04 124245](https://github.com/nfdi4plants/ARCitect/assets/127506066/b892284e-c84d-45d0-9a93-49e3b8989780)
![Screenshot 2023-09-04 124838](https://github.com/nfdi4plants/ARCitect/assets/127506066/71df3cfa-57b1-4a9e-bd0c-1ac982141e8f)

**Comment by JonasLukasczyk** [comment]
fixed
