### ISSUE TITLE
[BUG] Spaces in ARC identifier, failed upload

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#46]
**OS and framework information (please complete the following information):**
OS: Windows 11 Pro
Using ARCitect 0.0.5

**Describe the bug**
- When you use spaces in the name of the ARC (as identifier) the ARC cannot be uploaded to the DataHub
- spaces will be incorporated into your URL (Remote)
- upload is displayed as successful, altought the upload fails
- if you remove the spaces by hand from the URL, the upload works 

Idea: 
- don't allow spaces in the ARC name or don't allow spaces in the URL

![Screenshot 2023-09-06 114901](https://github.com/nfdi4plants/ARCitect/assets/127506066/40e5f6a2-5911-4ba6-b7f6-6c286954b465)
![Screenshot 2023-09-06 114918](https://github.com/nfdi4plants/ARCitect/assets/127506066/dde989d2-3138-4349-a27d-aa6b40fab61b)

**Comment by Brilator** [comment]
Seems to be fixed. Spaces are replaced by underscores _

**Comment by Freymaurer** [comment]
Yes ARCtrl should handle these now correctly for the ARCitect.
