### ISSUE TITLE
[BUG] update / reset buttons

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#48]
Update and reset buttons under a study or assay section Data don't work properly.

After adding (+) processes to a  **study**, both buttons remove all processes. 
After adding (+) processes to an  **assay**, none of the buttons has an effect. 

<img width="752" alt="Screenshot 2023-09-20 at 08 39 52" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/81494ce0-fdc5-4077-b10a-034f0233f1da">

- ARCitect v0.0.8
- macOS
- tested from source code `rpm run debug`

**Comment by JonasLukasczyk** [comment]
The SWATE integration is not stable at this point, but we will track this bug here for the v1.0.0 release anyway.

**Comment by Freymaurer** [comment]
This will be solved by #53. Closing this for now!
