### ISSUE TITLE
[Feature Request] Swate Integration ❗ 

### ISSUE THREAD

**Issue by JonasLukasczyk** [nfdi4plants/ARCitect#53]
The ARCtrl library currently has no API to apply a SWATE template.

**Comment by Freymaurer** [comment]
# Template Requirements for ARCtrl

- [ ] filter by author name
- [ ] filter by tag (and/or)
- [ ] filter by organisation
- [ ] search by name

![image](https://github.com/nfdi4plants/ARCitect/assets/39732517/66bcd39b-4acc-458f-bfe4-b5ceead9d0a3)

**Comment by Freymaurer** [comment]
# CompositeHeader

- [ ] Descriptions

**Comment by Freymaurer** [comment]
https://github.com/nfdi4plants/ARCtrl/pull/226

Will come with some utility functions:

- `import { Templates } from 'arctrl'` (please verify import from index.js works correctly), has functions to filter arrays of templates.
  - `Templates.getDistinctTags()`, `Templates.getDistinctEndpointRepositories()`, `getDistinctOntologyAnnotations()`
  - `Templates.filterByTags(tagArray)`, also exists for EndpointRepositories and OntologyAnnotations. Can be used with optional boolean input to toggle between OR and AND search. Default is false, is OR.

```js
const templates = [create_TestTemplate()];
const queryTags = [OntologyAnnotation.fromString("DNA"), OntologyAnnotation.fromString("RNA")];
Templates.filterByOntologyAnnotation(queryTags, true)(templates); //example for AND search
```

- `CompositeHeader` and `IOType` both have `getExplanation(caseName)`, which will return a string with a description. `caseName` can be used from `CompositeHeader.Cases`/`IOType.Cases`
- `Templates_fromJsonString ` will now return an array.
- `ArcTable.Join`, can be used to append one ArcTable to another. See source code comment. ⚠️for js `TableJoinOptions` can be any of "Headers" (Add only headers, no values), "WithUnit" (Add headers and unit information without main value), "WithValues" (Add full columns).

```fsharp
/// <summary>
/// This function can be used to join two arc tables.
/// </summary>
/// <param name="table">The table to join to this table.</param>
/// <param name="joinOptions">Can add only headers, header with unitized cell information, headers with values.</param>
/// <param name="forceReplace">if set to true will replace unique columns.</param>
member this.Join(table:ArcTable, ?joinOptions: TableJoinOptions, ?forceReplace: bool) : unit =
```

**Comment by Freymaurer** [comment]
Some name changes, read here: https://github.com/nfdi4plants/ARCtrl/pull/226

**Comment by Freymaurer** [comment]
Swate integration is coming along really well.

What needs to be done:

**ARCitect side**

- [ ] `SwateView.vue` needs logic to know if assay or study should be sent
- [ ] swate host selector option to allow in-Arcitect decision which swate host should be hosted in iframe.
  - store information in `AppProperties.ts`
  - persist information between sessions in arcitect config file?
  - Are there security concerns? Only allow certain hosts?

**Swate side**

- [ ] URL query parameter to check if inside ARCitect
- [ ] make sidebar expandable and move main functions to top bar buttons and dialogue
- [ ] disable metadata editing
