### ISSUE TITLE
[BUG] "Umlaute" cannot be used in assay/study identifier

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#60]
**OS and framework information (please complete the following information):**
OS: Windows 11 Pro
Using ARCitect 0.0.10

**Describe the bug**
- When you use a "Umlaut" ö ü ä in an identifier of assay or study the ARCitect crashes (wheel spins forever). In the developer tool you can see this error: 

![Screenshot 2023-10-05 124655](https://github.com/nfdi4plants/ARCitect/assets/127506066/bdc1f48b-4b77-456e-b562-23f3b0a076ad)

**Possible Solution**
- It would be great if there was a message like “These characters are not allowed” and then the option to use a different name

**Comment by Freymaurer** [comment]
This is added for assays in v0.0.16 and will be added for studies soon!
