### ISSUE TITLE
ORCID in Arcitect

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/ARCitect#62]
We received a feature request on 05/20/2023 via the DataPLANT help-desk mail:

"it would be nice to be able to search for ORCIDs in Arcitect (own and others)"

**Comment by Hannah-Doerpholz** [comment]
Also, in the ORCID field it is not clear whether to only give it the full link (with https://orcid.org/) or only the 16-digit number. The field should be described more clearly.

**Comment by Brilator** [comment]
- [ ] Make ORCID searchable (by providing first name + last name)
- [ ] retrieve last name, first name, affiliation, etc. after providing ORCID
- [ ] clarify presentation of ORCID (16-digit or URL)

**Comment by JonasLukasczyk** [comment]
currently the input follows a mask that forces you to enter the 16 digit number. If a URL is already stored in the ARC it will be converted to the number.

As of now you can auto complete the form by ORCID. The other way around is not supported by a REST API. In the future we might want to query a snapshot of all ORCID records as described here:
https://info.orcid.org/documentation/api-tutorials/api-tutorial-searching-the-orcid-registry/

Closing this issue for now.

**Comment by arendd** [comment]
Its still not possible to search for ORCID by first/last name, see comment above by @Brilator. Would be great to have this feature, because is not very convenient to search by the OCRID, usually no one knows his ORCID by heart. The public API provide such a function, should be easy to integrate.

**Comment by Freymaurer** [comment]
Hey! Since back then we changed a lot of logic around this topic, feel free to open a new issue in Swate: https://github.com/nfdi4plants/Swate; which is now responsible for isa xlsx file manipulation 🙂

**Comment by arendd** [comment]
> Hey! Since back then we changed a lot of logic around this topic, feel free to open a new issue in Swate: https://github.com/nfdi4plants/Swate; which is now responsible for isa xlsx file manipulation 🙂

Okay I can do this, but I don't get the relation? I'm talking about the ARCitect tool, I'm not using Swate !? So why not create it in this repository?

**Comment by Brilator** [comment]
Swate is now completely integrated into ARCitect. 

When clicking on an ISA part in ARCitect, what you see in the main panel is basically this: https://swate-alpha.nfdi4plants.org

But directly writing to the isa.*.xlsx files in your ARC
