### ISSUE TITLE
[Feature Request] Add "are you sure you want delete?" buttons

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#67]
**Is your feature request related to a problem? Please describe.**
We added a person and accidentally clicked the "remove person" button. 

**Describe the solution you'd like**
It would be nice to get another pop-up asking "are you sure you want to delete this entry?" before it gets irreversibly deleted.

**Comment by SabrinaZander** [comment]
This "Are you sure you want delete" message would also be nice for the deletion of publications.

**Comment by JonasLukasczyk** [comment]
This now needs to be addressed in SWATE (@Freymaurer)

**Comment by Freymaurer** [comment]
I think this is no longer necessary, as we have a undo/redo function in Swate 😃  So i think this can be closed

**Comment by Brilator** [comment]
Yes, undo / redo should do.
