### ISSUE TITLE
[Feature Request] Add options to delete individual studies and assays

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#68]
**Is your feature request related to a problem? Please describe.**
When I created an assay I accidentally also created a new study, which I didn't want. I could re-assign the assay but I was stuck with the remaining study. I then closed the ARCitect and manually deleted the study folder I didn't want. However, then I could now open the ARC anymore (likely because the study was still listed in the investigation.xlsx).

**Describe the solution you'd like**
We need a delete option for studies and assays respectively, that both deletes the respective folder, as well as updates the investigation.xlsx file.

**Describe alternatives you've considered**
It is probably possible to delete the folder manually and remove it from the investigation.xlsx, but this is not comfortable for the users since they have to know every place where the study/assay that shall be deleted is referenced.

**Comment by Brilator** [comment]
Could this be a solution: 

1. user deletes (study / assay) folder or edits the name "by hand"
2. ARCitect detects the change
3. ARCitect opens a pop-up "ARCitect detected that study / assay XYZ was deleted / the file name was updated. Are you sure you want to delete / edit the name?"
4. and offers two options: "undo change" "yes, update ARC / isa investigation"

**Comment by Freymaurer** [comment]
Added option to delete studies/assays from context menu (rightclick) on arc tree view :sparkles: beginning from v.0.0.17

**Comment by Freymaurer** [comment]
Ups: Will also enable deleting from folder directly, currently this should result in failing ARCs.

**Comment by Brilator** [comment]
> Ups: Will also enable deleting from folder directly, currently this should result in failing ARCs.

It doesn't. 
I can delete folders from ARC via Finder / Explorer. They disappear from ARCitect tree view, but will not be deleted from isa.investigation.xlsx

**Comment by Brilator** [comment]
Deleting assays / studies via ARCitect (v.0.0.20) works like a charm though (on macOS)!

**Comment by Freymaurer** [comment]
> > Ups: Will also enable deleting from folder directly, currently this should result in failing ARCs.
> 
> It doesn't. 
> I can delete folders from ARC via Finder / Explorer. They disappear from ARCitect tree view, but will not be deleted from isa.investigation.xlsx

This is the expected behaviour. ARCitect will soon feature a list of regustered studies/assays in invedtigation metadata, where this will be highlighted then
