### ISSUE TITLE
[BUG] git history / status buggy

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#71]
Direct user feedback: 

> ARCitect does not allow to commit changes / does not recognize changes although ARC was newly created and cannot upload it (maybe technical issue on my computer though?)

Not sure, which git installation / which OS, etc. (in this case) 
But this seems to be a recurrent issue

**Comment by Brilator** [comment]
More from users
> bug: No changes to commit altough changes were made

> bug: No upload possible: message "no changes to commit"

**Comment by Brilator** [comment]
I think this boils down to which / whether git is installed (independently of ARCitect)

**Comment by Freymaurer** [comment]
I will investigate but this could be a very specific issue. It would be best to have a step by step on how to trigger this issue.

**Comment by Brilator** [comment]
Cannot reproduce (on windows) with v0.0.20
