### ISSUE TITLE
[BUG] ARCitect logs out automatically? 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#72]
User: 
> ARCitect user logs out after a while, have to restart ARCitect again

- version 0.0.10
- macOS

**Comment by Brilator** [comment]
Possibly fixed by increasing token expiration time.
Needs to be tested though: this was token at key cloak, not gitlab.

**Comment by JonasLukasczyk** [comment]
Can we close this? I think this is not a bug.
