### ISSUE TITLE
[Feature Request]  possiblity to add data to run & worksflows

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#73]
User feedback

> no possiblity to add data to run & worksflows in the ARCitect yet (you can open your ARC in the folder insert it by hand)

**Comment by Freymaurer** [comment]
Like an `+` button which opens a file selector. The then selected file will be moved to the correct position?

**Comment by Brilator** [comment]
If I understood correctly, basically just the way you implemented it now analog to "add datasets" (just call it differently).
However, I would not suggest to implement every possible ARC / file handling into the ARCitect. 
Proper integrations of (e.g. CWLed) workflows and runs would require more than just adding the files. And the coders would know that.

**Comment by Freymaurer** [comment]
Related to #83 

Uses same logic as Datasets beginning from v0.0.17 ✨
