### ISSUE TITLE
[Feature Request] add "revert" mechanism 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#74]
Similar to #68, users asked for a "revert" button to revert changes

**Comment by Freymaurer** [comment]
This is a very difficult to manage request. Let's explore the following scenario:

> User deletes assay

This will also delete datasets and lfs files(?)

We would need to store these files as state to which we can revert. Which might be doable but sounds rather difficult.

Is it feasable to apply this "revert" mechanism only to ISA files? Maybe with a warning for assay/study deletion, which tells the user that these changes are irreversible?

Let me know what you think @Brilator

**Comment by Brilator** [comment]
> Is it feasable to apply this "revert" mechanism only to ISA files? Maybe with a warning for assay/study deletion, which tells the user that these changes are irreversible?

That's definitely the main use case. During learning and first trials phase (often before adding data), users create their ARCs without perfect IDs for studies and assays in mind and often want to change that after a short time.

**Comment by JonasLukasczyk** [comment]
Reverting via git is already possible and ISA files have an undo stack in SWATE. So I think we can close this issue for now. Correct @Brilator ?

**Comment by Brilator** [comment]
Yes! We've got revert in Swate. We've got reset. 
And I guess renaming is on the agenda #32
