### ISSUE TITLE
[Feature Request] add button "open in finder / explorer"

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#82]
Users keep working between ARCitect and Finder / Windows Explorer for several reasons:
- adding multiple files at once 
- moving instead of copying datasets / protocols (when using "add dataset") 
- working with workflows and runs
- adding non-ARC folders

So it might help to add a button in the sidebar to open the ARC there.

**Comment by Freymaurer** [comment]
a button to open file explorer in location?

**Comment by Brilator** [comment]
yes ... not an important feature, but I keep forgetting where I store my ARCs and especially during trainings I don't want to take participants through my whole file tree :D 

Alternative: write the path on top of the file tree in ARCitect in a copy-pastable way (without spaces between / )

**Comment by Freymaurer** [comment]
Added right here:
![image](https://github.com/nfdi4plants/ARCitect/assets/39732517/dc69435b-3790-4760-894f-efdc1496843c)

Please let me know if you have suggestions for naming/icon! This will be part of release 0.0.15 ✨
