### ISSUE TITLE
[Feature Request] Missing information in README.md

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#84]
**Is your feature request related to a problem? Please describe.**
- when downloading the AppImage (Ubuntu 20.04) I still need to make the file executable before I can run it

**Describe the solution you'd like**
- this information should be added to the Install instructions:
     #### Make the file executable
     ##### with the user interface
     - right-click the file and select properties
     - go to the "permissions" tab and tick the field "execute"

     ##### from the command line (you might need specific rights for this)
     - move to the directory where you have saved your AppImage (e.g. Downloads)
     ```cd Downloads```
     - make the file executable (use the appropriate name of the file)
     ```chmod u+x ARCitect-0.0.15.AppImage```

**Comment by Freymaurer** [comment]
Currently we publish linux as an AppImage, is there a better target for this? As far as i understand it, we could also publish to Flatpak or Snap?

**Comment by muehlhaus** [comment]
Hi Hannah,

Thank you for your valuable input. ARCitect is developed as an open-source project, and a pull request is more than welcome, especially from DataPLANT colleagues.

Best,
Timo

**Comment by Brilator** [comment]
Hi Hannah. Nice that someone tests ARCitect on linux as well. Can you do us a favor and add an installation guide to the kb, where you specify this? Thanks

**Comment by Hannah-Doerpholz** [comment]
I created a PR for this repo just now. I will also add a small guide for the kb.

**Comment by Freymaurer** [comment]
> Currently we publish linux as an AppImage, is there a better target for this? As far as i understand it, we could also publish to Flatpak or Snap?

@Hannah-Doerpholz

**Comment by Hannah-Doerpholz** [comment]
I'm unfortunately not that familiar with the development of software similar to the ARCitect (I'm mostly familiar with command line tools and package menagement for that). I think the AppImage is a really comfortable way, at least it is for me. Making files executable is not a big issue and has to be done in most cases for executables from GitHub (at least from my experience). And while I think many people who use Linux are probably familiar with this issue, I wanted to add these instructions for those who are actually not aware of it.
