### ISSUE TITLE
[BUG] Add colums/rows in Data table 

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#86]
Since version 0.11 I can no longer add columns/rows in the data table (Windows 11). 
Also if you press the update button the entire table is deleted

Version 0.10
![Screenshot 2023-11-16 124626](https://github.com/nfdi4plants/ARCitect/assets/127506066/ba6ebeb0-96f7-4b39-b4a5-30b27424dd28)

Version 0.15 
![Screenshot 2023-11-16 124709](https://github.com/nfdi4plants/ARCitect/assets/127506066/bdabe4b1-8e75-418c-baa6-3df94a9bf660)

**Comment by Freymaurer** [comment]
Hey thank you for your contribution, i am currently working on ARCitect issues and this will be on my list!

**Comment by SabrinaZander** [comment]
Thank you @Freymaurer, I just saw that you can insert new rows/columns with a right click in the newer versions. Unfortunately, this wasn't intuitive for me at all and I only saw it by chance. Maybe you can make an extra button for this or use the plus sign again.

**Comment by Freymaurer** [comment]
Will have a look at it, as soon as i get there 👍

**Comment by Freymaurer** [comment]
We will soon add a complete Swate like view in ARCitect, i will close this issue for now!
