### ISSUE TITLE
[BUG] New study input field requires enter instead of confirm on focus-loss

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#87]
- OS: Windows 11
 - ARCitect version 0.17

 Creating of a new study fails if it is created together with a new assay

- Steps to reproduce: 

1. Create new Assay with an Assay Identifier and a **new** Study Identifier
2. Add Assay
3. Assay folder will be added 
4. No new Study folder is added 

Expected behavior:
Studies that have not yet been created should be created as a new study folder together with the new assay folder

It worked in previous version, but I need to check when the bug occured

**Comment by Freymaurer** [comment]
Hello! Thanks for your input! I will have a look at this asap!

**Comment by Freymaurer** [comment]
I tested your steps to reproduce and they error did not occure to me in v0.0.19 (not yet published). Maybe the underlying issue was fixed as a secondary effect on some of the other changes. Please give it a try tomorrow with the new version and let me know if it still does not work!

**Comment by SabrinaZander** [comment]
It worked, but not as expected. After adding a study identifier, I need to press Enter. Otherwise, if you just select “Add Assay,” the study name will be removed and a new study will not be created. 

I have an idea where that comes from. In a previous version, e.g. 0.0.10, the name of the assay was also used as an identifier of the linked new study. Now there is the option to enter the study identifier as well, which is actually very cool. But the name would have to be fixed straight away without having to press enter first. Here are a few screenshots that hopefully make it clearer.

**v. 0.0.10**

![Screenshot 2023-11-21 203725](https://github.com/nfdi4plants/ARCitect/assets/127506066/6378f47c-8ac8-450b-977b-ad2c732f7313)

![Screenshot 2023-11-21 203712](https://github.com/nfdi4plants/ARCitect/assets/127506066/fa48f2ad-8ec7-4dc1-9b03-2c7a379cd343)

**v.0.0.19**
![Screenshot 2023-11-21 203820](https://github.com/nfdi4plants/ARCitect/assets/127506066/4311c5bb-761a-40ec-9565-e016ec646040)

After pressing enter: 
![Screenshot 2023-11-21 205045](https://github.com/nfdi4plants/ARCitect/assets/127506066/ef4fcd5d-f2cd-41ab-9ab3-825120cac1ff)

![Screenshot 2023-11-21 205148](https://github.com/nfdi4plants/ARCitect/assets/127506066/2d885d96-9b4d-467d-9229-2b69f3b07a6d)

I don't know if there is the possibility to add the name without pressing enter first. 
If you need further information, please let me know. Thank you very much for your effort.

**Comment by Freymaurer** [comment]
i see what you mean, maybe it should "auto-enter" whenever the input field looses focus. Let me see if i can fix that tomorrow

**Comment by Freymaurer** [comment]
Okay, this should be solved now. While i was at it, i also:

- Enabled checking for already existing assay identifiers
- Enabled live input validation while typing

Very happy with how it is designed now, let me know what you think. This will be live from v0.0.21 onwards ✨

**Comment by SabrinaZander** [comment]
Perfectly solved, thank you
