### ISSUE TITLE
[BUG] Git / Git LFS on macOS

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#89]
From the last trainings, it seems that git issues are solved for windows (ca. version ≤ 0.0.15).

So this is a collection of git-related issues for macOS:

- [ ] ARCitect does not hide gitignored files from file tree
- [x] ARCitect apparently recognizes system Git (shipped by default with newer macOS versions and / or when installing macOS Command Line Tools), but it does not find git-lfs (e.g. installed via homebrew) 
  - [x] ARCs with LFS files can only be downloaded using the workaround #88 

#71
#75

**Comment by Brilator** [comment]
Still exists on macOS

**Comment by Freymaurer** [comment]
Can we have a look at this tomorrow?

**Comment by Freymaurer** [comment]
> ARCitect does not add default gitignore https://github.com/nfdi4plants/ARCitect/issues/49

Just to verify. This is an issue when creating a fresh ARC?

**Comment by Brilator** [comment]
Sorry, my bad. I need to rephrase. 

1. The .gitignore **is added**. 
2. The ignored files are not pushed. 

The only thing is that ARCitect does not hide the ignored files from the file tree. 

<img width="1401" alt="Screenshot 2023-11-23 at 08 44 05" src="https://github.com/nfdi4plants/ARCitect/assets/16229676/3bde1fe8-4e65-4480-b969-490230c9538d">

**Comment by JonasLukasczyk** [comment]
It seems this is fixed sine [0.0.24](https://github.com/nfdi4plants/ARCitect/releases/tag/v0.0.24). @Brilator please confirm and then close.

**Comment by Brilator** [comment]
The gitignore part persists with 0.0.24. 
Ignored files are displayed in the file tree, but they are correctly listed in .gitignore and ignored on git commit.

**Comment by JonasLukasczyk** [comment]
Currently the tree view only omits common hidden files, not the ones according to the git ignore files. This logic is not implemented. As a hotfix I added the `.DS_Store` to the list of omitted files. I close this for now.
