### ISSUE TITLE
[Feature Request] Handling LFS files

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#91]
User feedback: 

> Download only needed files of one ARC through ARCitect, not clone the whole repo to local drive.
> Selectively download files/images 

Idea: 
1. Label LFS files in ARCitect tree as "LFS"
2. Select to download individual LFS files or folders (dataset) containing LFS files

**Comment by Brilator** [comment]
- More flexible way of selecting LFS files
- Make LFS threshold adaptable.

**Comment by Freymaurer** [comment]
Solved for now! Reopen if any further issues arise! Live from v0.0.24 by @JonasLukasczyk 🎉
