### ISSUE TITLE
[Feature Request] Info banner new versions

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#93]
User feedback:

Inform about new available ARCitect versions when opening the app with link to release page
(Maybe not for every sub-subversion)

**Comment by Freymaurer** [comment]
There is an option to create signed versions which would also enable auto-updates. I'll remember this issue

**Comment by JonasLukasczyk** [comment]
Starting with version 0.0.32 ARCitect will indicate next to the version of a new release is available.
