### ISSUE TITLE
[Feature Request] delete button for assays/studies

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#94]
Is it possible to add a delete button to studies and assays? Right-clicking to delete assays/studies was very unintuitive for me (I did't figure it out by myself :-)). Maybe a delete button next to the Update and Reset button would be an option.

**Comment by Freymaurer** [comment]
Absolutly! Will add this soon

**Comment by JonasLukasczyk** [comment]
Added in ba56112
