### ISSUE TITLE
[Feature Request] "Versions" not intuitive

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/ARCitect#97]
**Is your feature request related to a problem? Please describe.**
Instead of searching for the sync (from ARC Commander) option under "Versions", "Refresh ARC" was pressed. 
"Versions" is not intuitive for most users. 

**Describe the solution you'd like**
Suggestion: Replace with "HUB exchange" or something similar indicating that here, the exchange with the HUB can be done.

**Comment by JonasLukasczyk** [comment]
This button is now called Upload ARC.
