### ISSUE TITLE
[Feature Request] (enable to) show .gitignore

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/ARCitect#99]
**Is your feature request related to a problem? Please describe.**
.gitignore is not displayed im ARCitect.

**Describe the solution you'd like**
Either show it by default or enable users to see hidden files via request (e.g. tick a box). When this is possible, users can adapt .gitignore to their needs.

**Comment by JonasLukasczyk** [comment]
It is now possible to edit the .gitignore file inside ARCitect.
